// Admin Console labels shared by the console and the server (CSV export):
// audit actions are stored as codes and shown in the viewer's language.
import type { Lang } from '@/i18n';

const ACTIONS: Record<string, [string, string]> = {
  'code.create': ['Gerou código', 'Generated code'],
  'code.edit': ['Editou código', 'Edited code'],
  'code.extend': ['Estendeu validade', 'Extended validity'],
  'code.pause': ['Pausou código', 'Paused code'],
  'code.resume': ['Retomou código', 'Resumed code'],
  'code.revoke': ['Revogou código', 'Revoked code'],
  'code.restore': ['Restaurou código', 'Restored code'],
  'tenant.create': ['Criou cliente', 'Created client'],
  'tenant.update': ['Alterou cliente', 'Changed client'],
  'tenant.custom': ['Alterou pacote individual', 'Changed custom plan'],
  'tenant.suspend': ['Suspendeu cliente', 'Suspended client'],
  'tenant.reactivate': ['Reativou cliente', 'Reactivated client'],
  'tenant.convert': ['Converteu trial em pago', 'Converted trial to paid'],
  'tenant.seats': ['Aumentou lugares', 'Increased seats'],
  'tenant.invoice': ['Emitiu fatura', 'Issued invoice'],
  'tenant.reminder': ['Enviou lembrete de pagamento', 'Sent payment reminder'],
  'tenant.expired': ['Licença expirou', 'License expired'],
  'tenant.purged': ['Apagou dados revogados', 'Purged revoked data'],
  'user.register': ['Registou-se', 'Signed up'],
  'user.email_verified': ['Confirmou o email', 'Confirmed email'],
  'user.update': ['Alterou utilizador', 'Changed user'],
  'user.files_limits': ['Alterou limites de ficheiros', 'Changed file limits'],
  'user.disable': ['Desativou utilizador', 'Disabled user'],
  'user.enable': ['Reativou utilizador', 'Reactivated user'],
  'user.pause': ['Pausou utilizador', 'Paused user'],
  'user.reset_sent': ['Enviou reposição de password', 'Sent password reset'],
  'user.invite_resent': ['Reenviou convite', 'Resent invite'],
  'user.delete': ['Eliminou utilizador', 'Deleted user'],
  'plan.update': ['Alterou pacote', 'Changed plan'],
  'plan.modules': ['Alterou módulos do pacote', 'Changed plan modules'],
  'plan.trial': ['Alterou trial do pacote', 'Changed plan trial'],
  'plan.limits': ['Alterou limites do FREE', 'Changed FREE limits'],
  'plan.addon': ['Alterou preços do pacote individual', 'Changed custom plan prices'],
  'admin.grant': ['Deu acesso de admin', 'Granted admin access'],
  'admin.remove': ['Removeu acesso de admin', 'Removed admin access'],
  'admin.pause': ['Pausou acesso de admin', 'Paused admin access'],
  'admin.resume': ['Retomou acesso de admin', 'Resumed admin access'],
  'admin.role': ['Alterou papel de admin', 'Changed admin role'],
  'request.create': ['Pediu plano', 'Requested plan'],
  'request.approve': ['Aprovou pedido de plano', 'Approved plan request'],
  'request.reject': ['Recusou pedido de plano', 'Rejected plan request'],
  'auth.login': ['Iniciou sessão', 'Signed in'],
  'auth.login_failed': ['Falhou o início de sessão', 'Failed sign-in'],
  'auth.logout': ['Terminou sessão', 'Signed out'],
  'auth.reauth': ['Desbloqueou', 'Unlocked'],
  'auth.2fa_enabled': ['Ativou a 2FA', 'Enabled 2FA'],
  'auth.2fa_disabled': ['Desativou a 2FA', 'Disabled 2FA'],
  'auth.reset_requested': ['Pediu reposição de password', 'Requested password reset'],
  'auth.password_reset': ['Repôs a password', 'Reset password'],
  'account.password_changed': ['Mudou a password', 'Changed password'],
  'account.profile_updated': ['Alterou o perfil', 'Updated profile'],
  'account.session_ended': ['Terminou uma sessão', 'Ended a session'],
  'account.sessions_ended': ['Terminou outras sessões', 'Ended other sessions'],
  'account.exported': ['Exportou os dados', 'Exported data'],
  'account.deleted': ['Eliminou a própria conta', 'Deleted own account'],
  'vault.setup': ['Configurou o cofre', 'Set up the vault'],
  'vault.master_changed': ['Mudou a master password', 'Changed master password'],
  'vault.wiped': ['Apagou o cofre', 'Wiped the vault'],
  'share.link.create': ['Criou link público', 'Created public link'],
  'share.link.revoke': ['Removeu link público', 'Removed public link'],
  'share.folder.delete': ['Eliminou pasta partilhada', 'Deleted shared folder'],
  'share.member.add': ['Partilhou pasta', 'Shared folder'],
  'share.member.invite': ['Convidou para pasta', 'Invited to folder'],
  'trash.purged': ['Esvaziou o lixo', 'Emptied trash'],
  'api.blocked': ['Pedido bloqueado (API Playground)', 'Blocked request (API Playground)'],
  'seed.superadmin_created': ['Criou o super admin', 'Created super admin'],
};

export const actionLabel = (action: string, lang: Lang) => ACTIONS[action]?.[lang === 'en' ? 1 : 0] ?? action;

export const AREA_LABELS: Record<string, [string, string]> = {
  codes: ['Códigos', 'Codes'],
  clients: ['Clientes e licenças', 'Clients and licenses'],
  users: ['Utilizadores', 'Users'],
  plans: ['Pacotes e preços', 'Plans and pricing'],
  admins: ['Administradores', 'Administrators'],
  system: ['Sistema', 'System'],
};
export const areaLabel = (area: string, lang: Lang) => AREA_LABELS[area]?.[lang === 'en' ? 1 : 0] ?? area;
