// Management labels from Management.dc.html (MG_L, MG_EX, MG_RX): the UI is written in
// Portuguese like the prototype; mt() gives the English text when the app is in English.
export const MG_L: Array<[string, string]> = [
  ['Áreas Principais', 'Main Areas'],
  [
    'Cada área é também uma competência. Ao remover, as pessoas dessa área passam para a primeira da lista.',
    'Each area is also a skill. When you remove one, its people move to the first area in the list.',
  ],
  ['Adicionar', 'Add'],
  ['Níveis de Senioridade', 'Seniority Levels'],
  [
    'Ordem do menos para o mais experiente. Ao remover um nível, as pessoas passam para o nível abaixo.',
    'Ordered from least to most experienced. When you remove a level, its people move to the level below.',
  ],
  [
    'Repor pessoas, projetos, alocações e timesheets com os dados de exemplo.',
    'Reset people, projects, allocations and timesheets to the sample data.',
  ],
  ['Repor Dados', 'Reset Data'],
  ['Visão Geral', 'Overview'],
  ['Capacidade da Equipa · Próximas 12 Semanas', 'Team Capacity · Next 12 Weeks'],
  ['Alocado', 'Allocated'],
  ['Capacidade', 'Capacity'],
  ['Sobre-alocados', 'Over-allocated'],
  ['próx. 4 semanas', 'next 4 weeks'],
  ['Ninguém acima da capacidade.', 'No one over capacity.'],
  ['Disponíveis', 'Available'],
  ['≥ 16h livres / semana', '≥ 16h free / week'],
  ['Orçamento dos Projetos Ativos', 'Active Project Budgets'],
  ['Equipa', 'Team'],
  ['· desde', '· since'],
  ['Competências', 'Skills'],
  ['clique para mudar o nível', 'click to change the level'],
  ['+ Competência', '+ Skill'],
  ['Carga · Próximas 12 Semanas', 'Workload · Next 12 Weeks'],
  ['Alocações', 'Allocations'],
  ['Sem alocações ativas.', 'No active allocations.'],
  [
    'Clique numa célula para subir o nível; depois do último volta a vazio',
    'Click a cell to raise the level; after the last one it goes back to empty',
  ],
  ['Pessoa', 'Person'],
  ['Sénior + Expert', 'Senior + Expert'],
  ['Projetos', 'Projects'],
  ['■ Consumido', '■ Spent'],
  ['■ Previsão até ao fim (alocações)', '■ Forecast to completion (allocations)'],
  ['Fases', 'Phases'],
  ['+ Fase', '+ Phase'],
  ['Pedir Recurso', 'Request Resource'],
  ['Pedidos de Recurso', 'Staffing Requests'],
  ['Horas por semana · capacidade padrão 40h', 'Hours per week · default capacity 40h'],
  ['+ Alocação', '+ Allocation'],
  ['Média', 'Average'],
  ['Remover', 'Remove'],
  ['Cancelar', 'Cancel'],
  ['Guardar', 'Save'],
  ['Preenchido por', 'Filled by'],
  ['Reabrir', 'Reopen'],
  ['Candidatos Sugeridos', 'Suggested Candidates'],
  ['por competência, nível e disponibilidade no período', 'by skill, level and availability in the period'],
  ['livres', 'free'],
  ['Alocar', 'Allocate'],
  ['Ninguém com esta competência e nível.', 'No one with this skill and level.'],
  ['Timesheets', 'Timesheets'],
  ['Projeto', 'Project'],
  ['Total', 'Total'],
  ['· plano', '· plan'],
  ['Total /', 'Total /'],
  ['+ Adicionar Projeto', '+ Add Project'],
  ['Clientes', 'Clients'],
  ['+ Projeto', '+ Project'],
  ['Equipa Alocada Esta Semana', 'Team Allocated This Week'],
  ['Ninguém alocado esta semana.', 'No one allocated this week.'],
  ['Função por omissão', 'Default role'],
  ['Nova área (ex.: SAP IBP)', 'New area (e.g. SAP IBP)'],
  ['Função (ex.: Consultor IBP)', 'Role (e.g. IBP Consultant)'],
  ['Novo nível (ex.: Principal)', 'New level (e.g. Principal)'],
  ['Nova Pessoa', 'New Person'],
  ['Pesquisar nome, função, competência…', 'Search name, role, skill…'],
  ['Ocupação média nas próximas 4 semanas', 'Average workload over the next 4 weeks'],
  ['Remover Pessoa', 'Remove Person'],
  ['Filtrar pessoas…', 'Filter people…'],
  ['Novo Projeto', 'New Project'],
  ['Pesquisar código, nome, cliente…', 'Search code, name, client…'],
  ['Remover Projeto', 'Remove Project'],
  ['Remover Fase', 'Remove Phase'],
  ['Novo Pedido', 'New Request'],
  ['Remover Pedido', 'Remove Request'],
  ['Semana Anterior', 'Previous Week'],
  ['Semana Seguinte', 'Next Week'],
  ['Novo Cliente', 'New Client'],
  ['Remover Cliente', 'Remove Client'],
];
export const MG_EX: Record<string, string> = {
  // prompts and messages of the v2 screens (not in the prototype's tables)
  // Recursos: status, profile blocks, phone and experience breakdown
  Inativo: 'Inactive',
  Suspenso: 'Suspended',
  'Filtrar por estado': 'Filter by status',
  'Todos os estados': 'All statuses',
  '+ Nova área…': '+ New area…',
  '+ Novo nível…': '+ New level…',
  Disponibilidade: 'Availability',
  'Motivo / observações': 'Reason / notes',
  'Ex.: baixa médica até 30/11': 'E.g. sick leave until 30/11',
  Opcional: 'Optional',
  Experiência: 'Experience',
  'Função e equipa': 'Role and team',
  'Custos e capacidade': 'Cost and capacity',
  'Data de contratação': 'Hire date',
  'Anos de experiência': 'Years of experience',
  'Anos na empresa': 'Years at the company',
  'Calculado a partir da data de contratação': 'Worked out from the hire date',
  ano: 'year',
  anos: 'years',
  Telefone: 'Phone',
  'Carregar foto': 'Upload photo',
  'Mudar foto': 'Change photo',
  'Remover foto': 'Remove photo',
  'Não foi possível guardar a foto.': 'The photo could not be saved.',
  'Repartição da experiência': 'Experience breakdown',
  '{s} de {t} — excede': '{s} of {t} — over',
  '{l} por especificar': '{l} not yet assigned',
  'Tudo especificado': 'All assigned',
  'Anos em': 'Years in',
  Remover: 'Remove',
  'Área (ex.: HCM)': 'Area (e.g. HCM)',
  Área: 'Area',
  Anos: 'Years',
  '+ Área': '+ Area',
  '+ Especificar por área': '+ Break down by area',
  'Nome da nova área principal (ex.: SAP IBP)': 'Name of the new main area (e.g. SAP IBP)',
  'Função por omissão para esta área': 'Default role for this area',
  'Nome do novo nível de senioridade (ex.: Principal)': 'Name of the new seniority level (e.g. Principal)',
  'Não foi possível repor os dados.': 'Couldn’t reset the data.',
  Ordenar: 'Sort',
  Alocar: 'Allocate',
  Agrupar: 'Group',
  Dias: 'Days',
  'h/dia': 'h/day',
  'h/sem': 'h/wk',
  Recursos: 'Resources',
  Colaboradores: 'Collaborators',
  'Pesquisar Colaboradores': 'Find Collaborators',
  'Novo Colaborador': 'New Collaborator',
  'Pesquisar por nome, função ou área…': 'Search by name, role or area…',
  'Criar e Adicionar': 'Create and Add',
  'Indique o nome do colaborador.': 'Enter the collaborator name.',
  'Email inválido.': 'Invalid email.',
  'Ainda sem membros. Use "Adicionar membros".': 'No members yet. Use "Add Members".',
  'Sem equipa': 'No team',
  'Sem responsável': 'No lead',
  'Dados da Equipa': 'Team Details',
  'Adicionar Membros': 'Add Members',
  'Pessoas sem equipa aparecem primeiro. Cada pessoa pertence a uma só equipa.':
    'People without a team appear first. Each person belongs to one team only.',
  'Pesquisar membros…': 'Search members…',
  'Tornar responsável': 'Make lead',
  'Remover da equipa': 'Remove from team',
  'Ainda sem membros. Adicione pessoas na lista ao lado.':
    'No members yet. Add people from the list alongside.',
  'Ninguém encontrado.': 'No one found.',
  'Mover para esta equipa': 'Move to this team',
  Mover: 'Move',
  Adicionar: 'Add',
  Fechar: 'Close',
  Equipas: 'Teams',
  Equipa: 'Team',
  'Todas as equipas': 'All teams',
  'Gerir Equipas': 'Manage Teams',
  'Nova Equipa': 'New Team',
  Responsável: 'Lead',
  'Responsável (team lead)': 'Team lead',
  'Capacidade alvo (%)': 'Target utilization (%)',
  Descrição: 'Description',
  Cor: 'Color',
  'Áreas Principais': 'Main areas',
  Membros: 'Members',
  '+ Adicionar pessoa': '+ Add person',
  'Ver Painel': 'View Dashboard',
  Editar: 'Edit',
  'Editar Equipa': 'Edit Team',
  'Remover Equipa': 'Remove Team',
  Abaixo: 'Below',
  Dentro: 'Within',
  Acima: 'Above',
  'Agrupar por equipa': 'Group by team',
  'Desenvolvimento & Tecnologia': 'Development & Technology',
  'Finanças & Logística': 'Finance & Logistics',
  'Pessoas & PMO': 'People & PMO',
  'Desenvolvimento ABAP, Fiori, integração e Basis.': 'ABAP, Fiori, integration and Basis development.',
  'Consultoria funcional FI/CO e Logística.': 'FI/CO and Logistics functional consulting.',
  'HCM, SuccessFactors e gestão de projeto.': 'HCM, SuccessFactors and project management.',
  'Resource Finder': 'Resource Finder',
  'Nova Pesquisa': 'New Search',
  'Perfil Necessário': 'Required Profile',
  Competências: 'Skills',
  'Qualquer nível': 'Any level',
  '+ Competência': '+ Skill',
  'Custo/hora máx. (€)': 'Max cost/hour (€)',
  'Sem limite': 'No limit',
  Resultados: 'Results',
  Disponível: 'Available',
  'Ver Alocação': 'View Allocation',
  Alocado: 'Allocated',
  'ocupação no período': 'utilization in period',
  'Ninguém com este perfil.': 'No one matches this profile.',
  'Ordenar por disponibilidade': 'Sort by availability',
  'Ordenar por custo': 'Sort by cost',
  'Ordenar por nome': 'Sort by name',
  'Abrir Ficha Completa': 'Open Full Profile',
  'Carga · Próximas 12 Semanas': 'Workload · Next 12 Weeks',
  Alocações: 'Allocations',
  'Sem alocações ativas.': 'No active allocations.',
  'Painel de Alocação': 'Allocation Dashboard',
  'Abaixo da Alocação': 'Below Allocation',
  'Dentro da Alocação': 'Within Allocation',
  'Acima da Alocação': 'Above Allocation',
  'Esta Semana': 'This Week',
  'Próxima Semana': 'Next Week',
  'Próximas 4 Semanas': 'Next 4 Weeks',
  'Próximas 12 Semanas': 'Next 12 Weeks',
  '< 90% da capacidade': '< 90% of capacity',
  '90–100% da capacidade': '90–100% of capacity',
  '> 100% da capacidade': '> 100% of capacity',
  'Pesquisar pessoas…': 'Search people…',
  'Todas as áreas': 'All areas',
  'Todos os níveis': 'All levels',
  'Todos os clientes': 'All clients',
  'Todas as localizações': 'All locations',
  'Ocupação ↓': 'Utilization ↓',
  'Ocupação ↑': 'Utilization ↑',
  'Sem agrupamento': 'No grouping',
  'Agrupar por área': 'Group by area',
  'Agrupar por senioridade': 'Group by seniority',
  'Agrupar por localização': 'Group by location',
  'Limpar filtros': 'Clear filters',
  'Ninguém corresponde aos filtros.': 'No one matches the filters.',
  'média por semana': 'average per week',
  'Arraste para ajustar · duplo clique repõe': 'Drag to resize · double-click to reset',
  'Email do cliente inválido.': 'Invalid client email.',
  'Cliente Existente': 'Existing Client',
  Código: 'Code',
  Nome: 'Name',
  'Nome do cliente': 'Client name',
  'Criar Projeto': 'Create Project',
  Cancelar: 'Cancel',
  'Indique o nome do projeto.': 'Enter the project name.',
  'Indique o nome do novo cliente.': 'Enter the new client name.',
  'Escolha um cliente.': 'Choose a client.',
  'Por Pessoa': 'By Person',
  'Por Projeto': 'By Project',
  'Por Cliente': 'By Client',
  'Por Função': 'By Role',
  'Por Equipa': 'By Team',
  Semana: 'Week',
  '4 semanas': '4 Weeks',
  Planeado: 'Planned',
  Submetidos: 'Submitted',
  Total: 'Total',
  'Sem horas registadas ou planeadas neste período.': 'No hours logged or planned in this period.',
  Concluído: 'Done',
  Preenchido: 'Filled',
  Ativo: 'Active',
  'Em risco': 'At Risk',
  Aberto: 'Open',
  Proposto: 'Proposed',
  Rascunho: 'Draft',
  Submetido: 'Submitted',
  'Em falta': 'Missing',
  Todos: 'All',
  'Em aberto': 'Open',
  Preenchidos: 'Filled',
  'Todos os Projetos': 'All Projects',
  Timeline: 'Timeline',
  'Grelha Semanal': 'Weekly Grid',
  'Editar Alocação': 'Edit Allocation',
  'Nova Alocação': 'New Allocation',
  Pessoa: 'Person',
  Projeto: 'Project',
  'De (semana)': 'From (week)',
  'Até (semana)': 'To (week)',
  'Horas por semana': 'Hours per week',
  De: 'From',
  Até: 'To',
  Estado: 'Status',
  Competência: 'Skill',
  'Nível mínimo': 'Minimum level',
  Função: 'Role',
  'Área principal': 'Main area',
  Senioridade: 'Seniority',
  'Custo interno': 'Internal cost',
  'Preço de venda': 'Sell rate',
  Capacidade: 'Capacity',
  Localização: 'Location',
  Email: 'Email',
  Cliente: 'Client',
  Gestor: 'Manager',
  Orçamento: 'Budget',
  Início: 'Start',
  Fim: 'End',
  'Previsão final': 'Final forecast',
  Desvio: 'Variance',
  'Sem cliente': 'No client',
  Tipo: 'Type',
  Setor: 'Sector',
  Contacto: 'Contact',
  Externo: 'External',
  Interno: 'Internal',
  'Externo (consultoria)': 'External (consulting)',
  'Interno (equipa da empresa)': 'Internal (company team)',
  'Projetos ativos': 'Active projects',
  'Orçamento total': 'Total budget',
  Consumido: 'Spent',
  'Pessoas esta semana': 'People this week',
  'Ocupação · 4 semanas': 'Utilization · 4 weeks',
  'Equipa no limite': 'Team at capacity',
  'Capacidade livre': 'Spare capacity',
  'Dentro do previsto': 'On track',
  'Sobre-alocados': 'Over-allocated',
  'acima de 40h numa semana': 'over 40h in a week',
  Disponíveis: 'Available',
  '≥ 16h livres por semana': '≥ 16h free per week',
  'Pedidos de Recurso': 'Staffing requests',
  'abertos ou propostos': 'open or proposed',
  'Submeter Semana': 'Submit Week',
  Reabrir: 'Reopen',
  'Nova Pessoa': 'New Person',
  'Novo Projeto': 'New Project',
  'Novo Cliente': 'New Client',
  'Nova Fase': 'New Phase',
  Preparação: 'Preparation',
  Desenho: 'Design',
  Construção: 'Build',
  Testes: 'Testing',
  Suporte: 'Support',
  'Suporte contínuo': 'Ongoing Support',
  Execução: 'Execution',
  Energia: 'Energy',
  Retalho: 'Retail',
  Agroalimentar: 'Agri-food',
  Logística: 'Logistics',
  Saúde: 'Healthcare',
  'Equipa interna': 'Internal team',
  'Sistemas de Informação': 'Information Systems',
  Lisboa: 'Lisbon',
  Remoto: 'Remote',
  'A semana final tem de ser igual ou posterior à inicial.':
    'The end week must be the same as or after the start week.',
  'Repor todos os dados do Management (pessoas, projetos, alocações, timesheets) para os dados de exemplo?':
    'Reset all Management data (people, projects, allocations, timesheets) to the sample data?',
  Ninguém: 'No one',
};
export const MG_RX: Array<[RegExp, string]> = [
  [/ · (\d+) sem equipa$/, ' · $1 without a team'],
  [
    /^Remover a equipa (.+)\? As (\d+) pessoas ficam sem equipa\.$/,
    'Remove team $1? Its $2 people will have no team.',
  ],
  [/^1 colaborador$/, '1 member'],
  [/^(\d+) semanas$/, '$1 weeks'],
  [/^(\d+) colaboradores$/, '$1 members'],
  [/^alvo (\d+)%$/, 'target $1%'],
  [/(\d+) equipas/g, '$1 teams'],
  [/ · ocupação nas próximas 4 semanas$/, ' · utilization over the next 4 weeks'],
  [
    /^Remover a equipa (.+)\? As (\d+) pessoas passam para (.+)\.$/,
    'Remove team $1? Its $2 people will move to $3.',
  ],
  [/^(\d+) correspondem · (\d+) disponíveis$/, '$1 matches · $2 available'],
  [/ · (\d+) semanas$/, ' · $1 weeks'],
  [/^faltam (\d+)h$/, '$1h short'],
  [/h livres \/ semana$/, 'h free / week'],
  [/ sem alocação$/, ' unallocated'],
  [/^< 90% da capacidade/, '< 90% of capacity'],
  [/% da equipa$/, '% of team'],
  [/^(\d+) de (\d+)$/, '$1 of $2'],
  [/ grupos · /g, ' groups · '],
  [/(\d+) de (\d+) submetidos/g, '$1 of $2 submitted'],
  [/^Sem (\d)/, 'Wk $1'],
  [/(\d+) pessoas/g, '$1 people'],
  [/ projetos ativos · semana de /g, ' active projects · week of '],
  [/^Semana de /, 'Week of '],
  [/^(\d+) de (\d+) submetidos$/, '$1 of $2 submitted'],
  [/h\/semana/g, 'h/week'],
  [/h\/sem\b/g, 'h/wk'],
  [/h registadas nas últimas 4 semanas/, 'h logged in the last 4 weeks'],
  [/h alocadas de /, 'h allocated of '],
  [/h na semana de /, 'h in the week of '],
  [/ livres$/, ' free'],
  [/% orç\./, '% budget'],
  [/Média livre no período: /, 'Average free in period: '],
  [/ pedidas$/, ' requested'],
  [/ semanas\)/, ' weeks)'],
  [/^Consumido · /, 'Spent · '],
  [/^Remover o projeto (.+) e as suas alocações\?$/, 'Remove project $1 and its allocations?'],
  [/^Remover (.+) e as suas alocações\?$/, 'Remove $1 and their allocations?'],
  [
    /^(\d+) pessoa\(s\) têm a área (.+)\. Passam para (.+)\. Continuar\?$/,
    '$1 person(s) have the area $2. They will move to $3. Continue?',
  ],
  [
    /^(\d+) pessoa\(s\) estão em (.+)\. Passam para (.+)\. Continuar\?$/,
    '$1 person(s) are at $2. They will move to $3. Continue?',
  ],
  [
    /^(.+) tem (\d+) projeto\(s\)\. Remover mesmo assim\? Os projetos ficam sem cliente\.$/,
    '$1 has $2 project(s). Remove anyway? The projects will have no client.',
  ],
  [/^Seg /, 'Mon '],
  [/^Ter /, 'Tue '],
  [/^Qua /, 'Wed '],
  [/^Qui /, 'Thu '],
  [/^Sex /, 'Fri '],
  [/Developer ABAP/g, 'ABAP Developer'],
  [/Developer Fiori/g, 'Fiori Developer'],
  [/Arquiteto BTP/g, 'BTP Architect'],
  [/Gestor de projeto/g, 'Project Manager'],
  [/Gestão de projeto/g, 'Project Management'],
  [/Migração S\/4/g, 'S/4 Migration'],
  [/Consultor ([A-Za-z0-9\/]+(?: [A-Za-z0-9\/]+)?)(?=$| ·)/g, '$1 Consultant'],
  [/(^|[\s·(])Júnior(?=$|[\s·)])/g, '$1Junior'],
  [/(^|[\s·(])Pleno(?=$|[\s·)])/g, '$1Mid-level'],
  [/(^|[\s·(])Sénior(?=$|[\s·)])/g, '$1Senior'],
  [/ \(interno\)/g, ' (internal)'],
  [/^Semana /, 'Week '],
];

/** English text for a Portuguese Management label (prototype mgTr). */
export function mgTr(s: string, lang: string): string {
  if (lang !== 'en' || !/[A-Za-zÀ-ú]/.test(s)) return s;
  if (MG_EX[s] !== undefined) return MG_EX[s]!;
  let r = s;
  for (const [re, to] of MG_RX) r = r.replace(re, to);
  return r;
}
/** MG_L entry by index (prototype L.k<i>). */
export const mgL = (i: number, lang: string) => MG_L[i]![lang === 'en' ? 1 : 0];
