// Standard SAP transactions given to every tenant (Transações SAP): Basis (BC),
// ABAP development, HCM, MM and FI. Compiled from SAP Help / community lists;
// the program (TSTC-PGMNA) is filled only where it is known — empty otherwise.
// Types: dialog (module pool / screen), report, param (parameter transaction),
// oo (class method), area (area menu).
import type { TxType } from './sap';

export type TxSeed = [code: string, description: string, module: string, program: string, type: TxType];

// prettier-ignore
export const TX_CATALOG: TxSeed[] = [
  // ── Basis (BC) ──────────────────────────────────────────────────────────
  ['SU01', 'Manutenção de utilizadores', 'BC', 'SAPMSUU0', 'dialog'],
  ['SU01D', 'Visualizar utilizadores', 'BC', 'SAPMSUU0', 'dialog'],
  ['SU10', 'Manutenção de utilizadores em massa', 'BC', '', 'dialog'],
  ['SU02', 'Manutenção de perfis de autorização', 'BC', '', 'dialog'],
  ['SU03', 'Manutenção de autorizações', 'BC', '', 'dialog'],
  ['SU21', 'Manutenção de classes e objetos de autorização', 'BC', '', 'dialog'],
  ['SU22', 'Valores propostos de autorização (SAP)', 'BC', '', 'dialog'],
  ['SU24', 'Valores propostos de autorização (cliente)', 'BC', '', 'dialog'],
  ['SU25', 'Upgrade do gerador de perfis', 'BC', '', 'dialog'],
  ['SU53', 'Análise da última verificação de autorização', 'BC', '', 'dialog'],
  ['SU56', 'Buffer de autorizações do utilizador', 'BC', '', 'dialog'],
  ['SUIM', 'Sistema de informação de utilizadores', 'BC', '', 'dialog'],
  ['PFCG', 'Manutenção de funções (roles)', 'BC', 'SAPLPRGN_TREE', 'dialog'],
  ['PFUD', 'Comparação de utilizadores das funções', 'BC', '', 'report'],
  ['SM01', 'Bloquear / desbloquear transações', 'BC', '', 'dialog'],
  ['SM01_DEV', 'Bloquear transações (cliente atual)', 'BC', '', 'dialog'],
  ['SM02', 'Mensagens de sistema', 'BC', '', 'dialog'],
  ['SM04', 'Lista de utilizadores ligados', 'BC', 'RSM04000_ALV', 'report'],
  ['AL08', 'Utilizadores ligados em todos os servidores', 'BC', '', 'report'],
  ['SM12', 'Entradas de bloqueio (locks)', 'BC', 'SAPMSM12', 'dialog'],
  ['SM13', 'Registos de atualização (update)', 'BC', 'SAPMSM13', 'dialog'],
  ['SM14', 'Administração do update', 'BC', '', 'dialog'],
  ['SM19', 'Configuração do Security Audit Log', 'BC', '', 'dialog'],
  ['SM20', 'Análise do Security Audit Log', 'BC', '', 'report'],
  ['RSAU_CONFIG', 'Configuração do Security Audit Log (novo)', 'BC', '', 'dialog'],
  ['RSAU_READ_LOG', 'Leitura do Security Audit Log (novo)', 'BC', '', 'report'],
  ['SM21', 'Log de sistema', 'BC', 'RSYSLOG', 'report'],
  ['SM35', 'Sessões de batch input', 'BC', 'SAPMSBDC_CC', 'dialog'],
  ['SHDB', 'Gravador de batch input', 'BC', 'SAPMSBDC_CC', 'dialog'],
  ['SM36', 'Definir job em background', 'BC', '', 'dialog'],
  ['SM37', 'Visão geral de jobs', 'BC', 'SAPLBTCH', 'dialog'],
  ['SM39', 'Análise de jobs', 'BC', '', 'dialog'],
  ['SM49', 'Executar comandos externos do SO', 'BC', '', 'dialog'],
  ['SM69', 'Manter comandos externos do SO', 'BC', '', 'dialog'],
  ['SM50', 'Visão geral de processos de trabalho', 'BC', '', 'dialog'],
  ['SM51', 'Servidores de aplicação', 'BC', 'SAPMSM51', 'dialog'],
  ['SM66', 'Processos de trabalho em todo o sistema', 'BC', '', 'dialog'],
  ['SM58', 'RFC transacional (tRFC)', 'BC', '', 'report'],
  ['SM59', 'Destinos RFC', 'BC', '', 'dialog'],
  ['SMQ1', 'Monitor qRFC (fila de saída)', 'BC', '', 'dialog'],
  ['SMQ2', 'Monitor qRFC (fila de entrada)', 'BC', '', 'dialog'],
  ['SMGW', 'Monitor do gateway', 'BC', '', 'dialog'],
  ['SMICM', 'Monitor do ICM', 'BC', '', 'dialog'],
  ['SMLG', 'Grupos de logon', 'BC', '', 'dialog'],
  ['SM30', 'Manutenção de tabelas/vistas', 'BC', 'SAPMSVMA', 'dialog'],
  ['SM31', 'Manutenção de tabelas (antiga)', 'BC', 'SAPMSVMA', 'dialog'],
  ['SM34', 'Manutenção de clusters de vistas', 'BC', '', 'dialog'],
  ['SCC1', 'Cópia de cliente por ordem de transporte', 'BC', '', 'dialog'],
  ['SCC3', 'Log de cópias de cliente', 'BC', '', 'dialog'],
  ['SCC4', 'Administração de clientes (mandantes)', 'BC', '', 'dialog'],
  ['SCC5', 'Eliminar cliente', 'BC', '', 'dialog'],
  ['SCC7', 'Pós-processamento de importação de cliente', 'BC', '', 'dialog'],
  ['SCC8', 'Exportação de cliente', 'BC', '', 'dialog'],
  ['SCCL', 'Cópia de cliente local', 'BC', '', 'dialog'],
  ['SCC9', 'Cópia de cliente remota', 'BC', '', 'dialog'],
  ['STMS', 'Transport Management System', 'BC', '', 'dialog'],
  ['STMS_IMPORT', 'Fila de importação do TMS', 'BC', '', 'dialog'],
  ['SE01', 'Transport Organizer (vista alargada)', 'BC', '', 'dialog'],
  ['SE03', 'Ferramentas do Transport Organizer', 'BC', '', 'dialog'],
  ['SE06', 'Configurar o Transport Organizer', 'BC', '', 'dialog'],
  ['SE09', 'Transport Organizer', 'BC', 'RDDM0001', 'dialog'],
  ['SE10', 'Transport Organizer (customizing)', 'BC', 'RDDM0001', 'dialog'],
  ['SPAM', 'Gestor de Support Packages', 'BC', '', 'dialog'],
  ['SAINT', 'Instalador de add-ons', 'BC', '', 'dialog'],
  ['SNOTE', 'Assistente de notas SAP', 'BC', '', 'dialog'],
  ['SPAU', 'Ajuste de modificações (repositório)', 'BC', '', 'dialog'],
  ['SPDD', 'Ajuste de modificações (dicionário)', 'BC', '', 'dialog'],
  ['RZ03', 'Estados e modos de operação dos servidores', 'BC', '', 'dialog'],
  ['RZ04', 'Modos de operação', 'BC', '', 'dialog'],
  ['RZ10', 'Manutenção de perfis de parâmetros', 'BC', '', 'dialog'],
  ['RZ11', 'Manutenção de parâmetros de perfil', 'BC', '', 'dialog'],
  ['RZ12', 'Grupos de servidores RFC', 'BC', '', 'dialog'],
  ['RZ20', 'Monitor CCMS', 'BC', '', 'dialog'],
  ['RZ70', 'Registo no SLD', 'BC', '', 'dialog'],
  ['ST01', 'Trace do sistema', 'BC', '', 'dialog'],
  ['ST02', 'Monitor de buffers', 'BC', '', 'dialog'],
  ['ST03N', 'Monitor de carga de trabalho', 'BC', '', 'dialog'],
  ['ST04', 'Monitor de base de dados', 'BC', '', 'dialog'],
  ['ST05', 'Trace de performance (SQL)', 'BC', '', 'dialog'],
  ['ST06', 'Monitor do sistema operativo', 'BC', '', 'dialog'],
  ['ST11', 'Ficheiros de trace dos work processes', 'BC', '', 'dialog'],
  ['ST12', 'Trace único de transações', 'BC', '', 'dialog'],
  ['ST22', 'Análise de dumps ABAP', 'BC', '', 'dialog'],
  ['STAD', 'Estatísticas de transações', 'BC', '', 'dialog'],
  ['DB02', 'Monitor de espaço da base de dados', 'BC', '', 'dialog'],
  ['DB12', 'Monitor de backups da base de dados', 'BC', '', 'dialog'],
  ['DB13', 'Calendário de planeamento DBA', 'BC', '', 'dialog'],
  ['AL11', 'Diretórios do servidor de aplicação', 'BC', 'RSWATCH0', 'report'],
  ['CG3Y', 'Descarregar ficheiro do servidor', 'BC', '', 'dialog'],
  ['CG3Z', 'Carregar ficheiro para o servidor', 'BC', '', 'dialog'],
  ['SP01', 'Controlo de spool', 'BC', '', 'dialog'],
  ['SP02', 'Os meus pedidos de spool', 'BC', '', 'dialog'],
  ['SPAD', 'Administração de spool (impressoras)', 'BC', '', 'dialog'],
  ['SP12', 'Administração TemSe', 'BC', '', 'dialog'],
  ['SCOT', 'Administração SAPconnect', 'BC', '', 'dialog'],
  ['SOST', 'Monitor de envios SAPconnect', 'BC', '', 'dialog'],
  ['SBWP', 'SAP Business Workplace', 'BC', '', 'dialog'],
  ['SICF', 'Manutenção de serviços HTTP (ICF)', 'BC', '', 'dialog'],
  ['SOAMANAGER', 'Gestão de web services', 'BC', '', 'dialog'],
  ['SRT_UTIL', 'Ferramentas de diagnóstico de web services', 'BC', '', 'dialog'],
  ['SLG0', 'Objetos e subobjetos do log de aplicação', 'BC', '', 'dialog'],
  ['SLG1', 'Análise do log de aplicação', 'BC', '', 'dialog'],
  ['SLG2', 'Eliminar logs de aplicação expirados', 'BC', '', 'report'],
  ['SLICENSE', 'Administração de licenças', 'BC', '', 'dialog'],
  ['SECSTORE', 'Armazenamento seguro', 'BC', '', 'dialog'],
  ['STRUST', 'Gestor de certificados (PSE)', 'BC', '', 'dialog'],
  ['STRUSTSSO2', 'Certificados de logon único', 'BC', '', 'dialog'],
  ['SPRO', 'Customizing (IMG)', 'BC', '', 'dialog'],
  ['SCU3', 'Logs de alterações de tabelas', 'BC', '', 'dialog'],
  ['SCMP', 'Comparar vistas/tabelas entre sistemas', 'BC', '', 'dialog'],
  ['SCU0', 'Comparação de customizing', 'BC', '', 'dialog'],
  ['SALE', 'Customizing ALE', 'BC', '', 'dialog'],
  ['BD54', 'Sistemas lógicos', 'BC', '', 'param'],
  ['BD64', 'Modelo de distribuição ALE', 'BC', '', 'dialog'],
  ['BD87', 'Monitor de IDocs (reprocessamento)', 'BC', 'RBDMON00', 'report'],
  ['WE02', 'Visualizar IDocs', 'BC', 'RSEIDOC2', 'report'],
  ['WE05', 'Lista de IDocs', 'BC', 'RSEIDOC2', 'report'],
  ['WE19', 'Ferramenta de teste de IDocs', 'BC', '', 'dialog'],
  ['WE20', 'Acordos de parceiros', 'BC', '', 'dialog'],
  ['WE21', 'Portas', 'BC', '', 'dialog'],
  ['WE30', 'Tipos básicos de IDoc', 'BC', '', 'dialog'],
  ['WE31', 'Segmentos de IDoc', 'BC', '', 'dialog'],
  ['WE60', 'Documentação de IDocs', 'BC', '', 'dialog'],
  ['WE81', 'Tipos de mensagem lógicos', 'BC', '', 'param'],
  ['WE82', 'Tipos de mensagem e tipos de IDoc', 'BC', '', 'param'],
  ['SWDD', 'Workflow Builder', 'BC', '', 'dialog'],
  ['SWI1', 'Seleção de itens de trabalho (workflow)', 'BC', '', 'report'],
  ['SWI2_FREQ', 'Itens de trabalho por frequência', 'BC', '', 'report'],
  ['SWIA', 'Administração de itens de trabalho', 'BC', '', 'report'],
  ['SWU3', 'Customizing automático de workflow', 'BC', '', 'dialog'],
  ['SM62', 'Monitor de eventos de background', 'BC', '', 'dialog'],
  ['SM64', 'Disparar evento de background', 'BC', '', 'dialog'],
  ['SMX', 'Os meus jobs', 'BC', '', 'dialog'],
  ['SA38', 'Executar programa ABAP', 'BC', '', 'dialog'],
  ['SE16', 'Data Browser', 'BC', 'SAPLSETB', 'dialog'],
  ['SE16N', 'Browser de dados gerais', 'BC', 'SAPLSE16N', 'dialog'],
  ['SE16H', 'Browser de dados com agregação', 'BC', '', 'dialog'],
  ['SE17', 'Visualização geral de tabelas', 'BC', '', 'dialog'],
  ['SLDCHECK', 'Testar ligação ao SLD', 'BC', '', 'report'],
  ['SPPFCADM', 'Administração do PPF', 'BC', '', 'dialog'],

  // ── ABAP (desenvolvimento) ─────────────────────────────────────────────
  ['SE38', 'Editor ABAP', 'ABAP', 'RSABAPPROGRAM', 'report'],
  ['SE39', 'Editor em ecrã dividido', 'ABAP', '', 'dialog'],
  ['SE80', 'Object Navigator', 'ABAP', '', 'dialog'],
  ['SE11', 'ABAP Dictionary', 'ABAP', 'SAPMSRD0', 'dialog'],
  ['SE12', 'ABAP Dictionary (visualizar)', 'ABAP', 'SAPMSRD0', 'dialog'],
  ['SE14', 'Utilitário de base de dados', 'ABAP', '', 'dialog'],
  ['SE15', 'Sistema de informação do repositório', 'ABAP', '', 'dialog'],
  ['SE84', 'Sistema de informação do repositório (árvore)', 'ABAP', '', 'dialog'],
  ['SE18', 'BAdI Builder (definição)', 'ABAP', '', 'dialog'],
  ['SE19', 'BAdI Builder (implementação)', 'ABAP', '', 'dialog'],
  ['SE20', 'Enhancements', 'ABAP', '', 'dialog'],
  ['SE21', 'Package Builder', 'ABAP', '', 'dialog'],
  ['SE24', 'Class Builder', 'ABAP', '', 'dialog'],
  ['SE30', 'Análise de runtime (antiga)', 'ABAP', '', 'dialog'],
  ['SAT', 'Análise de runtime ABAP', 'ABAP', '', 'dialog'],
  ['SE32', 'Elementos de texto', 'ABAP', '', 'dialog'],
  ['SE36', 'Logical Database Builder', 'ABAP', '', 'dialog'],
  ['SE37', 'Function Builder', 'ABAP', 'SAPMS38L', 'dialog'],
  ['SE41', 'Menu Painter', 'ABAP', '', 'dialog'],
  ['SE43', 'Manutenção de menus de área', 'ABAP', '', 'dialog'],
  ['SE51', 'Screen Painter', 'ABAP', '', 'dialog'],
  ['SE54', 'Gerador de vistas de tabela', 'ABAP', '', 'dialog'],
  ['SE55', 'Gerador de diálogo de manutenção', 'ABAP', '', 'dialog'],
  ['SE61', 'Documentação (textos de diálogo)', 'ABAP', '', 'dialog'],
  ['SE63', 'Traduções', 'ABAP', '', 'dialog'],
  ['SE71', 'Formulários SAPscript', 'ABAP', '', 'dialog'],
  ['SE72', 'Estilos SAPscript', 'ABAP', '', 'dialog'],
  ['SE73', 'Manutenção de fontes SAPscript', 'ABAP', '', 'dialog'],
  ['SE75', 'Objetos e IDs de texto SAPscript', 'ABAP', '', 'dialog'],
  ['SE78', 'Gráficos de formulários', 'ABAP', '', 'dialog'],
  ['SMARTFORMS', 'SAP Smart Forms', 'ABAP', '', 'dialog'],
  ['SMARTSTYLES', 'Estilos Smart Forms', 'ABAP', '', 'dialog'],
  ['SFP', 'Formulários Adobe (Form Builder)', 'ABAP', '', 'dialog'],
  ['SE91', 'Manutenção de mensagens', 'ABAP', '', 'dialog'],
  ['SE93', 'Manutenção de transações', 'ABAP', 'SAPMSEUK', 'dialog'],
  ['SE95', 'Browser de modificações', 'ABAP', '', 'dialog'],
  ['SE97', 'Chamadas CALL TRANSACTION autorizadas', 'ABAP', '', 'dialog'],
  ['SMOD', 'Enhancements SAP (exits)', 'ABAP', '', 'dialog'],
  ['CMOD', 'Projetos de enhancement', 'ABAP', '', 'dialog'],
  ['SCI', 'Code Inspector', 'ABAP', '', 'dialog'],
  ['ATC', 'ABAP Test Cockpit', 'ABAP', '', 'dialog'],
  ['SLIN', 'Verificação estendida de programas', 'ABAP', '', 'dialog'],
  ['SAAB', 'Checkpoints ativáveis', 'ABAP', '', 'dialog'],
  ['SRTCM', 'Monitor de verificações de runtime', 'ABAP', '', 'dialog'],
  ['SEGW', 'SAP Gateway Service Builder', 'ABAP', '', 'dialog'],
  ['/IWFND/MAINT_SERVICE', 'Ativar e manter serviços OData', 'ABAP', '', 'dialog'],
  ['/IWFND/GW_CLIENT', 'Cliente Gateway (testar OData)', 'ABAP', '', 'dialog'],
  ['/IWFND/ERROR_LOG', 'Log de erros do Gateway', 'ABAP', '', 'dialog'],
  ['SPROXY', 'Enterprise Services Builder (proxies)', 'ABAP', '', 'dialog'],
  ['SXMB_MONI', 'Monitor de mensagens XI/PI', 'ABAP', '', 'dialog'],
  ['SWO1', 'Business Object Builder', 'ABAP', '', 'dialog'],
  ['BAPI', 'BAPI Explorer', 'ABAP', '', 'dialog'],
  ['SHMM', 'Monitor de objetos de memória partilhada', 'ABAP', '', 'dialog'],
  ['SNRO', 'Intervalos de numeração', 'ABAP', '', 'dialog'],
  ['SQVI', 'QuickViewer', 'ABAP', '', 'dialog'],
  ['SQ01', 'SAP Query — queries', 'ABAP', '', 'dialog'],
  ['SQ02', 'SAP Query — infosets', 'ABAP', '', 'dialog'],
  ['SQ03', 'SAP Query — grupos de utilizadores', 'ABAP', '', 'dialog'],
  ['SWO3', 'Business Object Repository (browser)', 'ABAP', '', 'dialog'],
  ['STVARV', 'Variáveis de seleção (TVARVC)', 'ABAP', '', 'dialog'],
  ['SE56', 'Visualizar tabela (antiga)', 'ABAP', '', 'dialog'],
  ['SAMC', 'Canais de mensagens ABAP', 'ABAP', '', 'dialog'],
  ['SAPC', 'Canais push ABAP', 'ABAP', '', 'dialog'],
  ['SCDO', 'Objetos de documentos de alteração', 'ABAP', '', 'dialog'],
  ['SCAT', 'Computer Aided Test Tool', 'ABAP', '', 'dialog'],
  ['SECATT', 'Testes eCATT', 'ABAP', '', 'dialog'],
  ['SUSG', 'Uso de código (SCMON) — agregação', 'ABAP', '', 'dialog'],
  ['SCMON', 'Monitor de chamadas ABAP', 'ABAP', '', 'dialog'],
  ['SYCM', 'Simplificação — código personalizado', 'ABAP', '', 'dialog'],

  // ── HCM ─────────────────────────────────────────────────────────────────
  ['PA10', 'Processo pessoal (personnel file)', 'HCM', '', 'dialog'],
  ['PA20', 'Visualizar dados mestre HR', 'HCM', 'SAPMP50A', 'dialog'],
  ['PA30', 'Manter dados mestre HR', 'HCM', 'SAPMP50A', 'dialog'],
  ['PA40', 'Medidas de pessoal', 'HCM', 'SAPMP50A', 'dialog'],
  ['PA41', 'Alterar dados de entrada', 'HCM', '', 'dialog'],
  ['PA42', 'Entrada rápida de medidas', 'HCM', '', 'dialog'],
  ['PA51', 'Visualizar dados de tempos', 'HCM', 'SAPMP50A', 'dialog'],
  ['PA61', 'Manter dados de tempos', 'HCM', 'SAPMP50A', 'dialog'],
  ['PA62', 'Lista de entrada de dados adicionais', 'HCM', '', 'dialog'],
  ['PA63', 'Manter dados de tempos (lista)', 'HCM', '', 'dialog'],
  ['PA70', 'Entrada rápida de dados mestre', 'HCM', '', 'dialog'],
  ['PA71', 'Entrada rápida de dados de tempos', 'HCM', '', 'dialog'],
  ['PA03', 'Registo de controlo do processamento salarial', 'HCM', '', 'dialog'],
  ['PA04', 'Intervalos de numeração de pessoal', 'HCM', '', 'dialog'],
  ['PA97', 'Matriz de remuneração', 'HCM', '', 'dialog'],
  ['PA98', 'Ajustes de remuneração', 'HCM', '', 'dialog'],
  ['PU00', 'Eliminar dados de pessoal', 'HCM', 'RPUDEL20', 'report'],
  ['PU01', 'Eliminar resultado de cálculo salarial atual', 'HCM', '', 'report'],
  ['PU03', 'Alterar estado do processamento salarial', 'HCM', '', 'dialog'],
  ['PU12', 'Interface Toolbox', 'HCM', '', 'dialog'],
  ['PU19', 'Tax Reporter', 'HCM', '', 'dialog'],
  ['PU30', 'Copiador de rubricas salariais', 'HCM', '', 'dialog'],
  ['PC00', 'Menu de processamento salarial', 'HCM', '', 'area'],
  ['PC00_M99_CALC', 'Cálculo salarial (internacional)', 'HCM', 'RPCALCX0', 'report'],
  ['PC00_M19_CALC', 'Cálculo salarial — Portugal', 'HCM', 'RPCALCP0', 'report'],
  ['PC00_M19_CEDT', 'Recibo de vencimento — Portugal', 'HCM', 'RPCEDTP0', 'report'],
  ['PC00_M99_CEDT', 'Recibo de vencimento (internacional)', 'HCM', 'RPCEDTX0', 'report'],
  ['PC00_M99_CIPE', 'Criar lançamento contabilístico do salário', 'HCM', 'RPCIPE00', 'report'],
  ['PC00_M99_CWTR', 'Relatório de rubricas salariais', 'HCM', 'H99CWTR0', 'report'],
  ['PC00_M99_PA03_RELEA', 'Libertar o processamento salarial', 'HCM', '', 'report'],
  ['PC00_M99_PA03_END', 'Terminar o processamento salarial', 'HCM', '', 'report'],
  ['PC00_M99_PA03_CORR', 'Libertar o processamento salarial para correções', 'HCM', '', 'report'],
  ['PC00_M99_DKON', 'Atribuição de rubricas a contas do Razão', 'HCM', '', 'report'],
  ['PC_PAYRESULT', 'Visualizar resultados do cálculo salarial', 'HCM', 'H99_DISPLAY_PAYRESULT', 'report'],
  ['PCP0', 'Processar execuções de lançamento', 'HCM', '', 'dialog'],
  ['PE01', 'Esquemas de cálculo', 'HCM', '', 'dialog'],
  ['PE02', 'Regras de cálculo (PCR)', 'HCM', '', 'dialog'],
  ['PE03', 'Características (features)', 'HCM', '', 'dialog'],
  ['PE04', 'Funções e operações', 'HCM', '', 'dialog'],
  ['PE51', 'Editor de formulários HR', 'HCM', '', 'dialog'],
  ['HRFORMS', 'HR Forms Workplace', 'HCM', '', 'dialog'],
  ['PT60', 'Avaliação de tempos', 'HCM', 'RPTIME00', 'report'],
  ['PT61', 'Folha de tempos', 'HCM', '', 'report'],
  ['PT62', 'Lista de presenças', 'HCM', '', 'report'],
  ['PT63', 'Plano de horário de trabalho pessoal', 'HCM', '', 'report'],
  ['PT64', 'Visão geral de ausências', 'HCM', '', 'report'],
  ['PT50', 'Visão geral de contingentes', 'HCM', '', 'dialog'],
  ['PT_ERL00', 'Extrato de tempos', 'HCM', 'RPTEDT00', 'report'],
  ['PT_QTA10', 'Gerar contingentes de ausência', 'HCM', '', 'report'],
  ['PT01', 'Criar plano de horário de trabalho', 'HCM', '', 'dialog'],
  ['CAT2', 'Introduzir folha de horas (CATS)', 'HCM', '', 'dialog'],
  ['CAT3', 'Visualizar folha de horas (CATS)', 'HCM', '', 'dialog'],
  ['CATS_APPR_LITE', 'Aprovar folhas de horas', 'HCM', '', 'report'],
  ['PP01', 'Manter objeto de gestão organizacional', 'HCM', 'SAPMH5A0', 'dialog'],
  ['PP02', 'Manutenção de objetos de OM (especialista)', 'HCM', 'SAPMH5A0', 'dialog'],
  ['PPOCE', 'Criar estrutura organizacional', 'HCM', '', 'dialog'],
  ['PPOME', 'Alterar estrutura organizacional', 'HCM', '', 'dialog'],
  ['PPOSE', 'Visualizar estrutura organizacional', 'HCM', '', 'dialog'],
  ['PO03', 'Manter posto (job)', 'HCM', 'SAPMH5A0', 'dialog'],
  ['PO10', 'Manter unidade organizacional', 'HCM', 'SAPMH5A0', 'dialog'],
  ['PO13', 'Manter posição', 'HCM', 'SAPMH5A0', 'dialog'],
  ['PO14', 'Manter tarefa', 'HCM', 'SAPMH5A0', 'dialog'],
  ['PFCT', 'Manutenção de tarefas (workflow)', 'HCM', '', 'dialog'],
  ['OOAW', 'Caminhos de avaliação', 'HCM', '', 'param'],
  ['OOCU', 'Customizing de gestão organizacional', 'HCM', '', 'dialog'],
  ['PM01', 'Criar / ampliar infotipos', 'HCM', '', 'dialog'],
  ['PB10', 'Recrutamento — dados do candidato', 'HCM', '', 'dialog'],
  ['PB30', 'Manter dados do candidato', 'HCM', '', 'dialog'],
  ['PB40', 'Medidas sobre candidatos', 'HCM', '', 'dialog'],
  ['PSV1', 'Gestão de eventos de formação', 'HCM', '', 'dialog'],
  ['PHAP_CATALOG', 'Catálogo de avaliações', 'HCM', '', 'dialog'],
  ['PPMDT', 'Manager\'s Desktop', 'HCM', '', 'dialog'],
  ['HRUSER', 'Configurar utilizadores ESS/MSS', 'HCM', '', 'dialog'],
  ['S_AHR_61016362', 'Relatório flexível de dados de colaboradores', 'HCM', '', 'report'],
  ['PECM_START_JOB_BDGT', 'Orçamento de remuneração', 'HCM', '', 'report'],

  // ── MM ──────────────────────────────────────────────────────────────────
  ['MM01', 'Criar material', 'MM', 'SAPLMGMM', 'dialog'],
  ['MM02', 'Modificar material', 'MM', 'SAPLMGMM', 'dialog'],
  ['MM03', 'Visualizar material', 'MM', 'SAPLMGMM', 'dialog'],
  ['MM06', 'Marcar material para eliminação', 'MM', '', 'dialog'],
  ['MM17', 'Alteração em massa de materiais', 'MM', '', 'dialog'],
  ['MM50', 'Ampliar vistas de material', 'MM', '', 'report'],
  ['MM60', 'Lista de materiais', 'MM', 'RMMVRZ00', 'report'],
  ['MMBE', 'Visão geral de stocks', 'MM', 'RMMMBESTN', 'report'],
  ['MMPV', 'Fechar período de materiais', 'MM', 'RMMMPERI', 'report'],
  ['MMRV', 'Permitir lançamentos no período anterior', 'MM', '', 'dialog'],
  ['MK01', 'Criar fornecedor (compras)', 'MM', 'SAPMF02K', 'dialog'],
  ['MK02', 'Modificar fornecedor (compras)', 'MM', 'SAPMF02K', 'dialog'],
  ['MK03', 'Visualizar fornecedor (compras)', 'MM', 'SAPMF02K', 'dialog'],
  ['XK01', 'Criar fornecedor (central)', 'MM', 'SAPMF02K', 'dialog'],
  ['XK02', 'Modificar fornecedor (central)', 'MM', 'SAPMF02K', 'dialog'],
  ['XK03', 'Visualizar fornecedor (central)', 'MM', 'SAPMF02K', 'dialog'],
  ['BP', 'Parceiro de negócio', 'MM', '', 'dialog'],
  ['ME01', 'Manter lista de fontes', 'MM', '', 'dialog'],
  ['ME11', 'Criar registo info', 'MM', 'SAPMM06I', 'dialog'],
  ['ME12', 'Modificar registo info', 'MM', 'SAPMM06I', 'dialog'],
  ['ME13', 'Visualizar registo info', 'MM', 'SAPMM06I', 'dialog'],
  ['ME51N', 'Criar requisição de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME52N', 'Modificar requisição de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME53N', 'Visualizar requisição de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME54N', 'Libertar requisição de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME55', 'Libertação coletiva de requisições', 'MM', '', 'report'],
  ['ME56', 'Atribuir fonte a requisições', 'MM', '', 'report'],
  ['ME57', 'Atribuir e processar requisições', 'MM', 'RM06BZ00', 'report'],
  ['ME59N', 'Criação automática de pedidos', 'MM', 'RM06BB30', 'report'],
  ['ME5A', 'Lista de requisições de compra', 'MM', 'RM06BA00', 'report'],
  ['ME41', 'Criar pedido de cotação (RFQ)', 'MM', 'SAPMM06E', 'dialog'],
  ['ME42', 'Modificar pedido de cotação', 'MM', 'SAPMM06E', 'dialog'],
  ['ME47', 'Manter cotação', 'MM', 'SAPMM06E', 'dialog'],
  ['ME49', 'Comparação de preços', 'MM', 'RM06EPS0', 'report'],
  ['ME21N', 'Criar pedido de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME22N', 'Modificar pedido de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME23N', 'Visualizar pedido de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME29N', 'Libertar pedido de compra', 'MM', 'SAPLMEGUI', 'dialog'],
  ['ME28', 'Libertação coletiva de pedidos', 'MM', '', 'report'],
  ['ME2L', 'Pedidos por fornecedor', 'MM', 'RM06EL00', 'report'],
  ['ME2M', 'Pedidos por material', 'MM', 'RM06EM00', 'report'],
  ['ME2N', 'Pedidos por número', 'MM', 'RM06EN00', 'report'],
  ['ME80FN', 'Análise geral de documentos de compra', 'MM', '', 'report'],
  ['ME9F', 'Mensagens de pedidos de compra', 'MM', '', 'report'],
  ['ME31K', 'Criar contrato', 'MM', 'SAPMM06E', 'dialog'],
  ['ME32K', 'Modificar contrato', 'MM', 'SAPMM06E', 'dialog'],
  ['ME33K', 'Visualizar contrato', 'MM', 'SAPMM06E', 'dialog'],
  ['ME31L', 'Criar programa de remessas', 'MM', 'SAPMM06E', 'dialog'],
  ['ME38', 'Manter divisões de remessa', 'MM', '', 'dialog'],
  ['MEK1', 'Criar condições de compra', 'MM', 'SAPMV13A', 'dialog'],
  ['ML81N', 'Folha de registo de serviços', 'MM', 'SAPLMLSR', 'dialog'],
  ['MIGO', 'Movimento de mercadorias', 'MM', 'SAPLMIGO', 'dialog'],
  ['MB01', 'Entrada de mercadorias para pedido (antiga)', 'MM', 'SAPMM07M', 'dialog'],
  ['MB1A', 'Saída de mercadorias (antiga)', 'MM', 'SAPMM07M', 'dialog'],
  ['MB1B', 'Transferência (antiga)', 'MM', 'SAPMM07M', 'dialog'],
  ['MB1C', 'Outras entradas de mercadorias (antiga)', 'MM', 'SAPMM07M', 'dialog'],
  ['MB03', 'Visualizar documento de material (antiga)', 'MM', 'SAPMM07M', 'dialog'],
  ['MBST', 'Estornar documento de material', 'MM', 'SAPMM07M', 'dialog'],
  ['MB21', 'Criar reserva', 'MM', 'SAPMM07R', 'dialog'],
  ['MB25', 'Lista de reservas', 'MM', 'RM07RESL', 'report'],
  ['MB51', 'Lista de documentos de material', 'MM', 'RM07DOCS', 'report'],
  ['MB52', 'Stocks em armazém', 'MM', 'RM07MLBS', 'report'],
  ['MB5B', 'Stocks numa data de lançamento', 'MM', 'RM07MLBD', 'report'],
  ['MB5T', 'Stock em trânsito', 'MM', '', 'report'],
  ['MB90', 'Processar mensagens de documentos de material', 'MM', '', 'report'],
  ['MSC1N', 'Criar lote', 'MM', 'SAPLCHRG', 'dialog'],
  ['MSC2N', 'Modificar lote', 'MM', 'SAPLCHRG', 'dialog'],
  ['MSC3N', 'Visualizar lote', 'MM', 'SAPLCHRG', 'dialog'],
  ['MI01', 'Criar documento de inventário físico', 'MM', 'SAPMM07I', 'dialog'],
  ['MI04', 'Introduzir contagem de inventário', 'MM', 'SAPMM07I', 'dialog'],
  ['MI07', 'Lançar diferenças de inventário', 'MM', 'SAPMM07I', 'dialog'],
  ['MI20', 'Lista de diferenças de inventário', 'MM', 'RM07IDIF', 'report'],
  ['MIRO', 'Introduzir fatura recebida', 'MM', 'SAPLMR1M', 'dialog'],
  ['MIR4', 'Visualizar fatura (MIRO)', 'MM', 'SAPLMR1M', 'dialog'],
  ['MIR6', 'Visão geral de faturas', 'MM', '', 'report'],
  ['MIR7', 'Pré-registar fatura recebida', 'MM', 'SAPLMR1M', 'dialog'],
  ['MR8M', 'Estornar fatura', 'MM', '', 'dialog'],
  ['MRBR', 'Libertar faturas bloqueadas', 'MM', 'RM08RELEASE', 'report'],
  ['MRRL', 'Liquidação automática (ERS)', 'MM', 'RMMR1MRS', 'report'],
  ['MR11', 'Manutenção da conta GR/IR', 'MM', '', 'dialog'],
  ['MRKO', 'Liquidação de consignação', 'MM', 'RMVKON00', 'report'],
  ['MD01', 'Planeamento MRP (total)', 'MM', '', 'dialog'],
  ['MD03', 'Planeamento MRP (material individual)', 'MM', '', 'dialog'],
  ['MD04', 'Lista de stocks/necessidades', 'MM', 'SAPMM61R', 'dialog'],
  ['MD05', 'Lista MRP individual', 'MM', '', 'dialog'],
  ['OMJJ', 'Customizing de tipos de movimento', 'MM', '', 'dialog'],
  ['OX10', 'Centros', 'MM', '', 'param'],
  ['OX09', 'Depósitos', 'MM', '', 'param'],
  ['OMS2', 'Tipos de material', 'MM', '', 'param'],
  ['OME9', 'Configuração de libertação (requisições)', 'MM', '', 'param'],

  // ── FI ──────────────────────────────────────────────────────────────────
  ['FB01', 'Lançar documento', 'FI', 'SAPMF05A', 'dialog'],
  ['FB02', 'Modificar documento', 'FI', 'SAPMF05L', 'dialog'],
  ['FB03', 'Visualizar documento', 'FI', 'SAPMF05L', 'dialog'],
  ['FB08', 'Estornar documento', 'FI', 'SAPMF05A', 'dialog'],
  ['FB09', 'Modificar item de documento', 'FI', 'SAPMF05L', 'dialog'],
  ['FB50', 'Lançamento em conta do Razão', 'FI', 'SAPMF05A', 'dialog'],
  ['FB60', 'Fatura de fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['FB65', 'Nota de crédito de fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['FB70', 'Fatura de cliente', 'FI', 'SAPMF05A', 'dialog'],
  ['FB75', 'Nota de crédito de cliente', 'FI', 'SAPMF05A', 'dialog'],
  ['FV50', 'Pré-registar documento do Razão', 'FI', 'SAPMF05A', 'dialog'],
  ['FV60', 'Pré-registar fatura de fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['FV70', 'Pré-registar fatura de cliente', 'FI', 'SAPMF05A', 'dialog'],
  ['FBV0', 'Lançar documento pré-registado', 'FI', 'SAPMF05V', 'dialog'],
  ['FBV3', 'Visualizar documento pré-registado', 'FI', '', 'dialog'],
  ['FBD1', 'Introduzir documento periódico', 'FI', 'SAPMF05A', 'dialog'],
  ['F.14', 'Executar documentos periódicos', 'FI', 'SAPF120', 'report'],
  ['F-02', 'Lançamento no Razão (geral)', 'FI', 'SAPMF05A', 'param'],
  ['F-03', 'Compensar conta do Razão', 'FI', 'SAPMF05A', 'dialog'],
  ['F-04', 'Lançar com compensação', 'FI', 'SAPMF05A', 'dialog'],
  ['F-28', 'Recebimento de cliente', 'FI', 'SAPMF05A', 'dialog'],
  ['F-32', 'Compensar cliente', 'FI', 'SAPMF05A', 'dialog'],
  ['F-43', 'Fatura de fornecedor (geral)', 'FI', 'SAPMF05A', 'dialog'],
  ['F-44', 'Compensar fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['F-47', 'Pedido de adiantamento a fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['F-48', 'Adiantamento a fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['F-53', 'Pagamento a fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['F-90', 'Aquisição de imobilizado com fornecedor', 'FI', 'SAPMF05A', 'dialog'],
  ['FB1D', 'Compensar cliente (manual)', 'FI', 'SAPMF05A', 'dialog'],
  ['FB1K', 'Compensar fornecedor (manual)', 'FI', 'SAPMF05A', 'dialog'],
  ['FB1S', 'Compensar conta do Razão (manual)', 'FI', 'SAPMF05A', 'dialog'],
  ['FBRA', 'Anular compensação', 'FI', 'SAPMF05R', 'dialog'],
  ['F.13', 'Compensação automática', 'FI', 'SAPF124', 'report'],
  ['F110', 'Programa de pagamentos automáticos', 'FI', 'SAPF110V', 'dialog'],
  ['FBZP', 'Customizing do programa de pagamentos', 'FI', '', 'dialog'],
  ['FCHN', 'Registo de cheques', 'FI', 'RFCHKN00', 'report'],
  ['FBL1N', 'Partidas individuais de fornecedor', 'FI', 'RFITEMAP', 'report'],
  ['FBL3N', 'Partidas individuais do Razão', 'FI', 'RFITEMGL', 'report'],
  ['FBL5N', 'Partidas individuais de cliente', 'FI', 'RFITEMAR', 'report'],
  ['FAGLL03', 'Partidas individuais do Razão (novo Razão)', 'FI', 'FAGL_ACCOUNT_ITEMS_GL', 'report'],
  ['FS10N', 'Saldos de conta do Razão', 'FI', '', 'dialog'],
  ['FAGLB03', 'Saldos de conta do Razão (novo Razão)', 'FI', '', 'dialog'],
  ['FK10N', 'Saldos de fornecedor', 'FI', '', 'dialog'],
  ['FD10N', 'Saldos de cliente', 'FI', '', 'dialog'],
  ['FS00', 'Manter conta do Razão (central)', 'FI', 'SAPLGL_ACCOUNT_MASTER_MAINTAIN', 'dialog'],
  ['FSS0', 'Manter conta do Razão (empresa)', 'FI', 'SAPLGL_ACCOUNT_MASTER_MAINTAIN', 'dialog'],
  ['FSP0', 'Manter conta do Razão (plano de contas)', 'FI', 'SAPLGL_ACCOUNT_MASTER_MAINTAIN', 'dialog'],
  ['FK01', 'Criar fornecedor (contabilidade)', 'FI', 'SAPMF02K', 'dialog'],
  ['FK02', 'Modificar fornecedor (contabilidade)', 'FI', 'SAPMF02K', 'dialog'],
  ['FK03', 'Visualizar fornecedor (contabilidade)', 'FI', 'SAPMF02K', 'dialog'],
  ['FD01', 'Criar cliente (contabilidade)', 'FI', 'SAPMF02D', 'dialog'],
  ['FD02', 'Modificar cliente (contabilidade)', 'FI', 'SAPMF02D', 'dialog'],
  ['FD03', 'Visualizar cliente (contabilidade)', 'FI', 'SAPMF02D', 'dialog'],
  ['XD01', 'Criar cliente (central)', 'FI', 'SAPMF02D', 'dialog'],
  ['XD02', 'Modificar cliente (central)', 'FI', 'SAPMF02D', 'dialog'],
  ['XD03', 'Visualizar cliente (central)', 'FI', 'SAPMF02D', 'dialog'],
  ['F.01', 'Balanço e demonstração de resultados', 'FI', 'RFBILA00', 'report'],
  ['S_ALR_87012284', 'Balanço / demonstração de resultados', 'FI', 'RFBILA00', 'report'],
  ['S_ALR_87012277', 'Saldos de contas do Razão', 'FI', '', 'report'],
  ['S_ALR_87012082', 'Saldos de fornecedores', 'FI', '', 'report'],
  ['S_ALR_87012172', 'Saldos de clientes', 'FI', '', 'report'],
  ['S_ALR_87012078', 'Análise de vencimentos de fornecedores', 'FI', '', 'report'],
  ['S_ALR_87012168', 'Análise de vencimentos de clientes', 'FI', '', 'report'],
  ['F.05', 'Avaliação de partidas em moeda estrangeira', 'FI', 'SAPF100', 'report'],
  ['FAGL_FC_VAL', 'Avaliação em moeda estrangeira (novo Razão)', 'FI', 'FAGL_FC_VALUATION', 'report'],
  ['F.81', 'Estorno de periodificações', 'FI', 'SAPF081', 'report'],
  ['FAGLGVTR', 'Transporte de saldos do Razão', 'FI', '', 'report'],
  ['F.07', 'Transporte de saldos de clientes/fornecedores', 'FI', '', 'report'],
  ['OB52', 'Abrir e fechar períodos contabilísticos', 'FI', '', 'param'],
  ['OB08', 'Taxas de câmbio', 'FI', '', 'param'],
  ['OBYC', 'Determinação automática de contas (MM)', 'FI', '', 'dialog'],
  ['FTXP', 'Códigos de IVA', 'FI', 'SAPMF82T', 'dialog'],
  ['OB40', 'Contas de IVA', 'FI', '', 'param'],
  ['S_ALR_87012357', 'Declaração de IVA (adiantamentos)', 'FI', '', 'report'],
  ['FF_5', 'Importar extrato bancário eletrónico', 'FI', 'RFEBKA00', 'report'],
  ['FF67', 'Extrato bancário manual', 'FI', 'SAPMF40K', 'dialog'],
  ['FEBAN', 'Pós-processamento de extratos bancários', 'FI', '', 'dialog'],
  ['FI12', 'Bancos da empresa', 'FI', '', 'dialog'],
  ['FI01', 'Criar banco', 'FI', '', 'dialog'],
  ['FBCJ', 'Diário de caixa', 'FI', 'SAPMFCJ0', 'dialog'],
  ['FBME', 'Menu de contabilidade bancária', 'FI', '', 'area'],
  ['AS01', 'Criar imobilizado', 'FI', 'SAPLAIST', 'dialog'],
  ['AS02', 'Modificar imobilizado', 'FI', 'SAPLAIST', 'dialog'],
  ['AS03', 'Visualizar imobilizado', 'FI', 'SAPLAIST', 'dialog'],
  ['AW01N', 'Explorador de imobilizado', 'FI', '', 'dialog'],
  ['AFAB', 'Execução de amortizações', 'FI', 'RAPOST2000', 'report'],
  ['ABUMN', 'Transferência de imobilizado', 'FI', '', 'dialog'],
  ['ABAVN', 'Abate de imobilizado (sucata)', 'FI', '', 'dialog'],
  ['AJAB', 'Fechar ano de imobilizado', 'FI', '', 'report'],
  ['AJRW', 'Mudança de ano fiscal (imobilizado)', 'FI', '', 'report'],
  ['S_ALR_87011990', 'Mapa de imobilizado', 'FI', '', 'report'],
  ['FAGLF101', 'Reclassificação de saldos (débito/crédito)', 'FI', '', 'report'],
  ['F150', 'Programa de cobranças (dunning)', 'FI', '', 'dialog'],
  ['FD32', 'Gestão de crédito de cliente', 'FI', '', 'dialog'],
  ['OBA7', 'Tipos de documento', 'FI', '', 'param'],
  ['OB41', 'Chaves de lançamento', 'FI', '', 'param'],
  ['OX02', 'Empresas', 'FI', '', 'param'],
  ['OBY6', 'Dados globais da empresa', 'FI', '', 'param'],
];
