import { S3Client, HeadBucketCommand } from '@aws-sdk/client-s3';
import { env } from '@/lib/env';

const g = globalThis as unknown as { __khS3?: S3Client };

// MinIO (S3-compatible). The bucket is private; files are only ever served
// through short-lived signed URLs generated by the app.
export function s3(): S3Client {
  const e = env();
  g.__khS3 ??= new S3Client({
    endpoint: e.S3_ENDPOINT,
    region: e.S3_REGION,
    forcePathStyle: e.S3_FORCE_PATH_STYLE,
    credentials: { accessKeyId: e.S3_ACCESS_KEY, secretAccessKey: e.S3_SECRET_KEY },
  });
  return g.__khS3;
}

export async function pingStorage(): Promise<void> {
  await s3().send(new HeadBucketCommand({ Bucket: env().S3_BUCKET }));
}
