// Starter catalog of well-known SAP transactions/apps, auto-seeded for every
// new user (and backfilled once for existing users via
// scripts/seed-transactions.js) so the Transações SAP page isn't empty on
// first visit. usageCount values are just plausible starting points so the
// "mais pesquisadas" quick-search list looks meaningful immediately.
export const DEFAULT_TRANSACTIONS = [
  // --- ABAP ---
  { tcode: 'SE38', description: 'Editor ABAP — criar e executar programas', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: true, usageCount: 58 },
  { tcode: 'SE80', description: 'Object Navigator — pacotes e objetos de desenvolvimento', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: true, usageCount: 55 },
  { tcode: 'SE11', description: 'ABAP Dictionary — tabelas, estruturas e domínios', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: true, usageCount: 52 },
  { tcode: 'SE37', description: 'Function Builder — criar/testar módulos de função', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 34 },
  { tcode: 'SE24', description: 'Class Builder — classes e interfaces ABAP OO', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 27 },
  { tcode: 'SE16N', description: 'Data Browser — visualizar/filtrar conteúdo de tabelas', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: true, usageCount: 47 },
  { tcode: 'SE91', description: 'Manutenção de classes de mensagens', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 12 },
  { tcode: 'SE93', description: 'Manter/criar códigos de transação', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 9 },
  { tcode: 'SE09 / SE10', description: 'Transport Organizer — ordens de transporte (Workbench/Customizing)', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 31 },
  { tcode: 'SLG1', description: 'Visualizar log de aplicação (Application Log)', module: 'ABAP', moduleGroup: 'ABAP', program: 'SBAL_DISPLAY', type: 'Report / Query', favorite: false, usageCount: 14 },
  { tcode: 'ST05', description: 'SQL/Performance Trace', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 11 },
  { tcode: 'SAT', description: 'Runtime Analysis — análise de performance de programas', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 8 },
  { tcode: 'CMOD / SMOD', description: 'Enhancements — user exits e SAP enhancements', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 10 },
  { tcode: 'SE51', description: 'Screen Painter — desenhar dynpros/ecrãs', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 7 },
  { tcode: 'SE71', description: 'SAPscript — layout sets (formulários clássicos)', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 4 },
  { tcode: 'SMARTFORMS', description: 'Smart Forms — desenhar formulários de output', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 9 },
  { tcode: 'SE18 / SE19', description: 'BAdI Builder — definição e implementação de BAdIs', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 13 },
  { tcode: 'SE84', description: 'Repository Information System — pesquisa de objetos', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Report / Query', favorite: false, usageCount: 6 },
  { tcode: 'ST12', description: 'Single Transaction Analysis — trace de performance combinado', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 5 },
  { tcode: 'SCI', description: 'Code Inspector — análise estática de qualidade de código', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 8 },
  { tcode: 'SLIN', description: 'Extended Program Check — verificação estática de sintaxe', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 6 },
  { tcode: 'SE63', description: 'Translation — tradução de textos e objetos', module: 'ABAP', moduleGroup: 'ABAP', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },

  // --- Basis ---
  { tcode: 'SM30', description: 'Manutenção de tabelas de customizing', module: 'Basis', moduleGroup: 'Basis', program: 'RSVTPROT', type: 'Customizing (SPRO)', favorite: true, usageCount: 39 },
  { tcode: 'SPRO', description: 'SAP Reference IMG — customizing central', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Customizing (SPRO)', favorite: true, usageCount: 35 },
  { tcode: 'ST22', description: 'Análise de dumps ABAP (runtime errors)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 22 },
  { tcode: 'SM37', description: 'Monitorizar jobs em background', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 24 },
  { tcode: 'SM36', description: 'Agendar novo job em background', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 13 },
  { tcode: 'SM21', description: 'System Log — eventos e erros do sistema', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 9 },
  { tcode: 'SM50 / SM66', description: 'Visão geral de work processes (local/global)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 7 },
  { tcode: 'SU01', description: 'Manutenção de utilizadores', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 17 },
  { tcode: 'PFCG', description: 'Manutenção de roles/perfis de autorização', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 15 },
  { tcode: 'STMS', description: 'Transport Management System', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 12 },
  { tcode: 'SICF', description: 'Manter serviços HTTP (ICF)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 6 },
  { tcode: 'SU03', description: 'Manutenção manual de perfis de autorização (legacy)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },
  { tcode: 'SU24', description: 'Objetos de autorização propostos por transação', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Customizing (SPRO)', favorite: false, usageCount: 5 },
  { tcode: 'SM19 / SM20', description: 'Configurar e visualizar o Security Audit Log', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 4 },
  { tcode: 'ST02', description: 'Tune Summary — estatísticas de buffers', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Report / Query', favorite: false, usageCount: 6 },
  { tcode: 'ST03N', description: 'Workload Analysis — tempos de resposta do sistema', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Report / Query', favorite: false, usageCount: 8 },
  { tcode: 'ST04', description: 'Database Performance Monitor', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Report / Query', favorite: false, usageCount: 5 },
  { tcode: 'DB02', description: 'Administração da base de dados — tablespaces/schemas', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 7 },
  { tcode: 'SM12', description: 'Visualizar/eliminar lock entries', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 14 },
  { tcode: 'SM13', description: 'Monitor de update requests (V1/V2)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 4 },
  { tcode: 'SM51', description: 'Lista de instâncias/servidores de aplicação', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },
  { tcode: 'SM04 / AL08', description: 'Utilizadores ligados (instância local / todo o sistema)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 6 },
  { tcode: 'SP01', description: 'Pedidos de output/spool', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 9 },
  { tcode: 'SPAD', description: 'Administração de spool e impressoras', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },
  { tcode: 'RZ10', description: 'Manutenção de parâmetros de perfil', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 4 },
  { tcode: 'RZ20', description: 'CCMS — Alert Monitor', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Report / Query', favorite: false, usageCount: 3 },
  { tcode: 'SCC4', description: 'Administração de clientes (clients)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Customizing (SPRO)', favorite: false, usageCount: 5 },
  { tcode: 'SM59', description: 'Manutenção de destinos RFC', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 11 },
  { tcode: 'SAINT / SPAM', description: 'Instalação de support packages e add-ons', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 2 },
  { tcode: 'SPAU / SPDD', description: 'Ajuste de modificações após upgrade', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 2 },
  { tcode: 'STAD', description: 'Estatísticas de performance por transação/utilizador', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Report / Query', favorite: false, usageCount: 4 },
  { tcode: 'AL11', description: 'Estrutura de diretorias do SAP (filesystem)', module: 'Basis', moduleGroup: 'Basis', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },

  // --- HCM: Personnel Administration ---
  { tcode: 'PA20', description: 'Visualizar dados mestre de RH', module: 'HCM · PA', moduleGroup: 'HCM', program: 'SAPMP50A', type: 'Transação Standard', favorite: true, usageCount: 45 },
  { tcode: 'PA30', description: 'Manter dados mestre de RH', module: 'HCM · PA', moduleGroup: 'HCM', program: 'SAPMP50A', type: 'Transação Standard', favorite: true, usageCount: 43 },
  { tcode: 'PA40', description: 'Executar ação de pessoal (admissão, transferência…)', module: 'HCM · PA', moduleGroup: 'HCM', program: 'SAPMP50A', type: 'Transação Standard', favorite: false, usageCount: 26 },
  { tcode: 'PA10', description: 'Ficheiro de pessoal (Personnel File)', module: 'HCM · PA', moduleGroup: 'HCM', program: '—', type: 'Report / Query', favorite: false, usageCount: 10 },
  { tcode: 'PA61', description: 'Manter dados de tempo de um colaborador', module: 'HCM · PA', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 12 },
  { tcode: 'PA71', description: 'Entrada rápida de dados de tempo (fast entry)', module: 'HCM · PA', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 6 },
  { tcode: 'PA41', description: 'Alterar data de nascimento (correção de dados mestre)', module: 'HCM · PA', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 2 },

  // --- HCM: Time Management ---
  { tcode: 'PT60', description: 'Lista de presenças/faltas', module: 'HCM · PT', moduleGroup: 'HCM', program: 'RPTABS20', type: 'Report / Query', favorite: false, usageCount: 18 },
  { tcode: 'PT01', description: 'Criar horário de trabalho', module: 'HCM · PT', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 7 },
  { tcode: 'CAT2', description: 'Registo de folha de horas (CATS)', module: 'HCM · PT', moduleGroup: 'HCM', program: 'SAPMCATT', type: 'Transação Standard', favorite: false, usageCount: 16 },
  { tcode: 'CAT3', description: 'Visualizar folha de horas (CATS)', module: 'HCM · PT', moduleGroup: 'HCM', program: 'SAPMCATT', type: 'Transação Standard', favorite: false, usageCount: 9 },
  { tcode: 'CATA', description: 'Aprovar registos de folha de horas', module: 'HCM · PT', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 8 },
  { tcode: 'PT_QTA00', description: 'Overview de quotas de ausência', module: 'HCM · PT', moduleGroup: 'HCM', program: '—', type: 'Report / Query', favorite: false, usageCount: 8 },
  { tcode: 'PT50', description: 'Time Manager\'s Workplace — gestão de tempo da equipa', module: 'HCM · PT', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 5 },
  { tcode: 'PT90', description: 'Extrato de tempo (Time Statement) do colaborador', module: 'HCM · PT', moduleGroup: 'HCM', program: '—', type: 'Report / Query', favorite: false, usageCount: 4 },

  // --- HCM: Payroll ---
  { tcode: 'PC00_M99_CALC', description: 'Executar folha de pagamento (driver internacional)', module: 'HCM · PY', moduleGroup: 'HCM', program: 'RPCALCX0', type: 'Report / Query', favorite: false, usageCount: 14 },
  { tcode: 'PC_PAYRESULT', description: 'Visualizar resultados de folha de pagamento', module: 'HCM · PY', moduleGroup: 'HCM', program: '—', type: 'Report / Query', favorite: false, usageCount: 11 },
  { tcode: 'PU19', description: 'Wage Type Reporter — onde é usado um tipo de rubrica', module: 'HCM · PY', moduleGroup: 'HCM', program: '—', type: 'Report / Query', favorite: false, usageCount: 5 },
  { tcode: 'PU01', description: 'Criar/manter tipos de rubrica (wage types)', module: 'HCM · PY', moduleGroup: 'HCM', program: '—', type: 'Customizing (SPRO)', favorite: false, usageCount: 6 },
  { tcode: 'PC00_M99_CEDT', description: 'Extrato de remuneração (Remuneration Statement)', module: 'HCM · PY', moduleGroup: 'HCM', program: '—', type: 'Report / Query', favorite: false, usageCount: 9 },
  { tcode: 'PA03', description: 'Manter registo de controlo da folha de pagamento', module: 'HCM · PY', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 7 },

  // --- HCM: Organizational Management ---
  { tcode: 'PPOME', description: 'Alterar estrutura organizativa', module: 'HCM · OM', moduleGroup: 'HCM', program: 'SAPLRHCH', type: 'Transação Standard', favorite: true, usageCount: 29 },
  { tcode: 'PPOSE', description: 'Visualizar estrutura organizativa', module: 'HCM · OM', moduleGroup: 'HCM', program: 'SAPLRHCH', type: 'Transação Standard', favorite: false, usageCount: 19 },
  { tcode: 'PPOCE', description: 'Criar organização e staffing (unidade organizativa nova)', module: 'HCM · OM', moduleGroup: 'HCM', program: 'SAPLRHCH', type: 'Transação Standard', favorite: false, usageCount: 6 },
  { tcode: 'PO10', description: 'Alterar unidade organizativa (formulário simples)', module: 'HCM · OM', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 4 },
  { tcode: 'PO13', description: 'Alterar posição (formulário simples)', module: 'HCM · OM', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 5 },
  { tcode: 'PO03', description: 'Alterar cargo/função (job)', module: 'HCM · OM', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },

  // --- HCM: Recruitment ---
  { tcode: 'PB10', description: 'Registo inicial de dados de candidato', module: 'HCM · Recrutamento', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 4 },
  { tcode: 'PB20', description: 'Alterar dados mestre de candidato', module: 'HCM · Recrutamento', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },
  { tcode: 'PB40', description: 'Executar ação de candidato (avançar no processo)', module: 'HCM · Recrutamento', moduleGroup: 'HCM', program: '—', type: 'Transação Standard', favorite: false, usageCount: 3 },

  // --- HCM: Benefits ---
  { tcode: 'HRBEN0001', description: 'Inscrição em planos de benefícios', module: 'HCM · Benefícios', moduleGroup: 'HCM', program: 'RPUBEN01', type: 'Transação Standard', favorite: false, usageCount: 2 },

  // --- SuccessFactors ---
  { tcode: 'Employee Central', description: 'Registo e manutenção de dados de colaboradores', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: true, usageCount: 33 },
  { tcode: 'Manage Business Configuration', description: 'Ativar/configurar objetos do EC (MDF/MBC)', module: 'SuccessFactors · MDF', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 20 },
  { tcode: 'Manage Data', description: 'Criar/editar registos de qualquer objeto MDF', module: 'SuccessFactors · MDF', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 21 },
  { tcode: 'Manage Permission Roles', description: 'Configurar permissões RBP', module: 'SuccessFactors · RBP', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 16 },
  { tcode: 'Manage Permission Groups', description: 'Definir grupos de utilizadores para RBP', module: 'SuccessFactors · RBP', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 9 },
  { tcode: 'Provisioning', description: 'Configuração ao nível do sistema (acesso restrito)', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 6 },
  { tcode: 'Position Management', description: 'Criar/gerir posições da estrutura organizativa', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 13 },
  { tcode: 'Import and Export Data', description: 'Carregar/exportar dados em massa (ficheiros CSV)', module: 'SuccessFactors · MDF', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 15 },
  { tcode: 'Manage Job Requisitions', description: 'Gerir pedidos de recrutamento', module: 'SuccessFactors · Recruiting', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 7 },
  { tcode: 'Manage Learning Activities', description: 'Gerir cursos e atividades de formação (LMS)', module: 'SuccessFactors · LMS', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 5 },
  { tcode: 'Manage Compensation Plans', description: 'Configurar planos de compensação', module: 'SuccessFactors · Comp', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 4 },
  { tcode: 'Employee Central Payroll Control Center', description: 'Monitorização do processo de payroll (EC Payroll)', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 8 },
  { tcode: 'Manage Templates', description: 'Gerir templates (email, onboarding, offboarding, MDF)', module: 'SuccessFactors · MDF', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 10 },
  { tcode: 'Company Settings', description: 'Definições globais da instância (idiomas, formatos, logotipo)', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 6 },
  { tcode: 'Manage Organization, Pay and Job Structures', description: 'Configurar estruturas de organização, pay e job', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 11 },
  { tcode: 'Employee Files', description: 'Gestão de documentos e ficheiros do colaborador', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 7 },
  { tcode: 'Manage Time Off', description: 'Configurar tipos e políticas de ausência (EC Time)', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 9 },
  { tcode: 'Manage Time Account Types', description: 'Configurar contas de tempo (EC Time)', module: 'SuccessFactors · EC', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 5 },
  { tcode: 'Manage Job Profiles', description: 'Gerir Job Profile Builder (descrições de função)', module: 'SuccessFactors · MDF', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 4 },
  { tcode: 'Manage Goal Plan Templates', description: 'Configurar templates de planos de objetivos', module: 'SuccessFactors · Performance', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 6 },
  { tcode: 'Calibration', description: 'Sessões de calibração de avaliações de desempenho', module: 'SuccessFactors · Performance', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 3 },
  { tcode: 'Succession Org Chart', description: 'Organograma de sucessão e planeamento de talento', module: 'SuccessFactors · Succession', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 5 },
  { tcode: 'Compensation Home', description: 'Ponto de entrada para ciclos de compensação', module: 'SuccessFactors · Comp', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 4 },
  { tcode: 'Variable Pay Home', description: 'Gestão de planos de remuneração variável', module: 'SuccessFactors · Comp', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 2 },
  { tcode: 'Manage Workflow Groups', description: 'Configurar grupos e regras de workflow', module: 'SuccessFactors · Workflow', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 5 },
  { tcode: 'Intelligent Services Center', description: 'Hub de eventos e integrações entre módulos SF', module: 'SuccessFactors · Integração', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 3 },
  { tcode: 'Candidate Profile', description: 'Perfil e histórico de candidatura (Recruiting)', module: 'SuccessFactors · Recruiting', moduleGroup: 'SuccessFactors', program: '—', type: 'Admin Tool (SF)', favorite: false, usageCount: 4 },
];
