import { Router } from 'express';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { prisma } from '../lib/prisma.js';
import { requireAuth, requireAuthAllowSuspended, requireAdmin } from '../middleware/auth.js';
import { DEFAULT_TRANSACTIONS } from '../lib/defaultTransactions.js';

const router = Router();

function signToken(userId) {
  return jwt.sign({ sub: userId }, process.env.JWT_SECRET, { expiresIn: '30d' });
}

function generateInviteCode() {
  return crypto.randomBytes(6).toString('base64url').toUpperCase();
}

function publicUser(user) {
  return {
    id: user.id,
    email: user.email,
    name: user.name,
    createdAt: user.createdAt,
    isTeamMember: !!user.teamOwnerId,
    role: user.role,
    status: user.status,
    hostingerConnected: !!user.settings?.hostingerApiTokenEnc,
    settings: user.settings
      ? {
          theme: user.settings.theme,
          accentColor: user.settings.accentColor,
          accentHue: user.settings.accentHue,
          fontFamily: user.settings.fontFamily,
          language: user.settings.language,
          logoUrl: user.settings.logoUrl,
          avatarUrl: user.settings.avatarUrl,
          vaultAutoLockSeconds: user.settings.vaultAutoLockSeconds,
          issueStatuses: user.settings.issueStatuses,
          trashRetentionDays: user.settings.trashRetentionDays,
          sidebarLayout: user.settings.sidebarLayout,
          homeLayout: user.settings.homeLayout,
        }
      : null,
  };
}

// Public sign-up is invite-only: every new independent account requires a
// valid, unused invite code generated by an admin. The account created is
// always fully independent (its own workspace) — the code only unlocks
// registration, it never joins the creator's team/data.
router.post('/register', async (req, res) => {
  const { email, password, name, inviteCode } = req.body || {};
  if (!email || !password || !name) {
    return res.status(400).json({ error: 'email, password and name are required' });
  }
  if (password.length < 8) {
    return res.status(400).json({ error: 'Password must be at least 8 characters' });
  }
  if (!inviteCode || !inviteCode.trim()) {
    return res.status(400).json({ error: 'An invite code is required', code: 'INVITE_CODE_REQUIRED' });
  }

  const invite = await prisma.inviteCode.findUnique({ where: { code: inviteCode.trim().toUpperCase() } });
  if (!invite || invite.usedAt || invite.revokedAt) {
    return res.status(400).json({ error: 'This invite code is invalid, already used, or has been revoked', code: 'INVITE_CODE_INVALID' });
  }

  const existing = await prisma.user.findUnique({ where: { email: email.toLowerCase() } });
  if (existing) return res.status(409).json({ error: 'An account with this email already exists' });

  const passwordHash = await bcrypt.hash(password, 12);

  const user = await prisma.$transaction(async (tx) => {
    const created = await tx.user.create({
      data: {
        email: email.toLowerCase(),
        passwordHash,
        name,
        settings: { create: {} },
      },
      include: { settings: true },
    });
    await tx.inviteCode.update({ where: { id: invite.id }, data: { usedAt: new Date(), usedById: created.id } });
    await tx.sapTransaction.createMany({
      data: DEFAULT_TRANSACTIONS.map((t) => ({ ...t, userId: created.id })),
    });
    return created;
  });

  const token = signToken(user.id);
  res.status(201).json({ token, user: publicUser(user) });
});

router.post('/login', async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) return res.status(400).json({ error: 'email and password are required' });

  const user = await prisma.user.findUnique({
    where: { email: email.toLowerCase() },
    include: { settings: true },
  });
  if (!user) return res.status(401).json({ error: 'Invalid email or password' });

  const valid = await bcrypt.compare(password, user.passwordHash);
  if (!valid) return res.status(401).json({ error: 'Invalid email or password' });

  const token = signToken(user.id);
  res.json({ token, user: publicUser(user) });
});

router.get('/me', requireAuthAllowSuspended, async (req, res) => {
  const user = await prisma.user.findUnique({
    where: { id: req.userId },
    include: { settings: true },
  });
  if (!user) return res.status(404).json({ error: 'User not found' });
  res.json({ user: publicUser(user) });
});

router.patch('/me', requireAuth, async (req, res) => {
  const { name } = req.body || {};
  const data = {};
  if (name !== undefined) {
    if (!name.trim()) return res.status(400).json({ error: 'Name cannot be empty' });
    data.name = name.trim();
  }
  const user = await prisma.user.update({
    where: { id: req.userId },
    data,
    include: { settings: true },
  });
  res.json({ user: publicUser(user) });
});

router.post('/change-password', requireAuth, async (req, res) => {
  const { currentPassword, newPassword } = req.body || {};
  if (!currentPassword || !newPassword) {
    return res.status(400).json({ error: 'currentPassword and newPassword are required' });
  }
  if (newPassword.length < 8) {
    return res.status(400).json({ error: 'New password must be at least 8 characters' });
  }

  const user = await prisma.user.findUnique({ where: { id: req.userId } });
  if (!user) return res.status(404).json({ error: 'User not found' });

  const valid = await bcrypt.compare(currentPassword, user.passwordHash);
  if (!valid) return res.status(401).json({ error: 'Current password is incorrect' });

  const passwordHash = await bcrypt.hash(newPassword, 12);
  await prisma.user.update({ where: { id: user.id }, data: { passwordHash } });
  res.json({ ok: true });
});

// Passwords (zero-knowledge ciphertext, useless outside this app) and Agent
// tokens (sensitive) are deliberately excluded from the export.
router.get('/export', requireAuth, async (req, res) => {
  const userId = req.effectiveUserId;
  const [user, notes, folders, tasks, tags, voiceNotes, issues, artifacts] = await Promise.all([
    prisma.user.findUnique({ where: { id: userId } }),
    prisma.note.findMany({ where: { userId } }),
    prisma.folder.findMany({ where: { userId } }),
    prisma.task.findMany({ where: { userId } }),
    prisma.tag.findMany({ where: { userId } }),
    prisma.voiceNote.findMany({ where: { userId } }),
    prisma.issue.findMany({ where: { userId } }),
    prisma.artifact.findMany({ where: { userId } }),
  ]);

  const exportData = {
    exportedAt: new Date().toISOString(),
    account: { email: user.email, name: user.name, createdAt: user.createdAt },
    notes,
    folders,
    tasks,
    tags,
    voiceNotes,
    issues,
    artifacts,
  };

  res.setHeader('Content-Disposition', 'attachment; filename="knowledge-hub-export.json"');
  res.json(exportData);
});

// Team members share the inviter's workspace data (Notes/Tasks/Tags/Voice/
// Folders/Issues/Artifacts) via req.effectiveUserId, but keep their own
// login, Passwords vault and Agent tokens — see middleware/auth.js.
router.get('/team', requireAuth, async (req, res) => {
  const me = await prisma.user.findUnique({ where: { id: req.userId } });
  const ownerId = me.teamOwnerId || me.id;
  const owner = me.teamOwnerId ? await prisma.user.findUnique({ where: { id: ownerId } }) : me;
  const members = await prisma.user.findMany({ where: { teamOwnerId: ownerId }, orderBy: { createdAt: 'asc' } });
  res.json({
    isOwner: !me.teamOwnerId,
    owner: { id: owner.id, name: owner.name, email: owner.email },
    members: members.map((m) => ({ id: m.id, name: m.name, email: m.email, createdAt: m.createdAt })),
  });
});

router.post('/team/invite', requireAuth, async (req, res) => {
  const me = await prisma.user.findUnique({ where: { id: req.userId } });
  if (me.teamOwnerId) return res.status(403).json({ error: 'Only the team owner can invite members' });

  const { name, email, password } = req.body || {};
  if (!name || !email || !password) return res.status(400).json({ error: 'name, email and password are required' });
  if (password.length < 8) return res.status(400).json({ error: 'Password must be at least 8 characters' });

  const existing = await prisma.user.findUnique({ where: { email: email.toLowerCase() } });
  if (existing) return res.status(409).json({ error: 'An account with this email already exists' });

  const passwordHash = await bcrypt.hash(password, 12);
  const member = await prisma.user.create({
    data: { email: email.toLowerCase(), passwordHash, name, teamOwnerId: me.id, settings: { create: {} } },
  });
  res.status(201).json({ member: { id: member.id, name: member.name, email: member.email, createdAt: member.createdAt } });
});

router.delete('/team/:memberId', requireAuth, async (req, res) => {
  const me = await prisma.user.findUnique({ where: { id: req.userId } });
  if (me.teamOwnerId) return res.status(403).json({ error: 'Only the team owner can remove members' });

  const member = await prisma.user.findFirst({ where: { id: req.params.memberId, teamOwnerId: me.id } });
  if (!member) return res.status(404).json({ error: 'Team member not found' });

  await prisma.user.delete({ where: { id: member.id } });
  res.status(204).end();
});

// --- Invite codes (admin only) ---------------------------------------

router.get('/invite-codes', requireAuth, requireAdmin, async (req, res) => {
  const codes = await prisma.inviteCode.findMany({
    orderBy: { createdAt: 'desc' },
    include: {
      createdBy: { select: { name: true, email: true } },
      usedBy: { select: { id: true, name: true, email: true } },
    },
  });
  res.json({
    codes: codes.map((c) => ({
      id: c.id,
      code: c.code,
      createdAt: c.createdAt,
      createdBy: c.createdBy,
      usedAt: c.usedAt,
      usedBy: c.usedBy,
      revokedAt: c.revokedAt,
    })),
  });
});

router.post('/invite-codes', requireAuth, requireAdmin, async (req, res) => {
  let code;
  for (let attempt = 0; attempt < 5; attempt += 1) {
    code = generateInviteCode();
    // eslint-disable-next-line no-await-in-loop
    const clash = await prisma.inviteCode.findUnique({ where: { code } });
    if (!clash) break;
    code = null;
  }
  if (!code) return res.status(500).json({ error: 'Could not generate a unique code, try again' });

  const invite = await prisma.inviteCode.create({ data: { code, createdById: req.userId } });
  res.status(201).json({ code: invite });
});

router.delete('/invite-codes/:id', requireAuth, requireAdmin, async (req, res) => {
  const invite = await prisma.inviteCode.findUnique({ where: { id: req.params.id } });
  if (!invite) return res.status(404).json({ error: 'Invite code not found' });
  if (invite.usedAt) return res.status(400).json({ error: 'This code has already been used and cannot be revoked' });
  await prisma.inviteCode.update({ where: { id: invite.id }, data: { revokedAt: new Date() } });
  res.status(204).end();
});

// --- Account management (admin only) ---------------------------------
// The super_admin account can only ever be changed by itself (via the
// normal /me and /change-password routes) — never through these endpoints,
// and admins can't act on their own account here either (avoids an admin
// accidentally locking themselves out).

router.get('/admin/users', requireAuth, requireAdmin, async (req, res) => {
  const users = await prisma.user.findMany({
    where: { role: { not: 'super_admin' } },
    orderBy: { createdAt: 'desc' },
    select: { id: true, name: true, email: true, role: true, status: true, createdAt: true, teamOwnerId: true },
  });
  res.json({ users });
});

router.patch('/admin/users/:id', requireAuth, requireAdmin, async (req, res) => {
  if (req.params.id === req.userId) return res.status(403).json({ error: 'Use your own account settings to manage yourself' });

  const target = await prisma.user.findUnique({ where: { id: req.params.id } });
  if (!target) return res.status(404).json({ error: 'User not found' });
  if (target.role === 'super_admin') return res.status(403).json({ error: 'The super admin account cannot be managed by other admins' });

  const { status, role } = req.body || {};
  const data = {};
  if (status !== undefined) {
    if (!['active', 'suspended'].includes(status)) return res.status(400).json({ error: 'status must be active or suspended' });
    data.status = status;
  }
  if (role !== undefined) {
    if (!['member', 'admin'].includes(role)) return res.status(400).json({ error: 'role must be member or admin' });
    data.role = role;
  }

  const updated = await prisma.user.update({ where: { id: target.id }, data });
  res.json({ user: { id: updated.id, name: updated.name, email: updated.email, role: updated.role, status: updated.status } });
});

router.delete('/admin/users/:id', requireAuth, requireAdmin, async (req, res) => {
  if (req.params.id === req.userId) return res.status(403).json({ error: 'Use your own account settings to manage yourself' });

  const target = await prisma.user.findUnique({ where: { id: req.params.id } });
  if (!target) return res.status(404).json({ error: 'User not found' });
  if (target.role === 'super_admin') return res.status(403).json({ error: 'The super admin account cannot be deleted' });

  await prisma.user.delete({ where: { id: target.id } });
  res.status(204).end();
});

export default router;
